
export const templatesV1_electoral: Template[] = [
    {
        id: 'elec-juicio-proteccion-derechos-v1',
        slug: 'juicio-proteccion-derechos-politicos',
        title: 'Juicio para la Proteccion de los Derechos Politico-Electorales',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/juicio-proteccion-derechos-politicos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 79-86 LGSMIME","Art. 99 Fr. V CPEUM"],
        description: 'Medio de impugnacion ante el TEPJF para defender derechos de votar, ser votado y asociarse politicamente.',
        keywords: ["JDC Electoral","TEPJF derechos politicos","amparo electoral ciudadano"],
    },
    {
        id: 'elec-recurso-apelacion-v1',
        slug: 'recurso-apelacion-resolucion-ine',
        title: 'Recurso de Apelacion contra Resolucion del INE',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/recurso-apelacion-resolucion-ine.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 40-52 LGSMIME","Art. 99 Fr. III CPEUM"],
        description: 'Recurso ante el TEPJF contra resoluciones del INE sobre fiscalizacion, registro de candidatos o sanciones.',
        keywords: ["recurso apelacion electoral TEPJF","impugnar resolucion INE","apelar sancion INE"],
    },
    {
        id: 'elec-juicio-revision-partido-v1',
        slug: 'juicio-revision-acto-partido-politico',
        title: 'Juicio para la Revision de Actos de Partido Politico',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/juicio-revision-acto-partido-politico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 87-104 LGSMIME"],
        description: 'Medio de impugnacion de ciudadanos contra resoluciones internas de su partido que afecten sus derechos.',
        keywords: ["demanda partido politico interno","JDC contra partido","derechos militante electoral"],
    },
    {
        id: 'elec-impugnacion-resultados-v1',
        slug: 'juicio-impugnacion-resultados-eleccion',
        title: 'Juicio de Inconformidad contra Resultados Electorales',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/juicio-impugnacion-resultados-eleccion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 53-78 LGSMIME"],
        description: 'Impugnacion formal de los resultados de una eleccion ante el TEPJF o tribunal local.',
        keywords: ["impugnar resultados eleccion","anular eleccion","TEPJF inconformidad"],
    },
    {
        id: 'elec-recurso-revision-ine-v1',
        slug: 'recurso-revision-regional-ine',
        title: 'Recurso de Revision ante el INE',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/recurso-revision-regional-ine.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 35-39 LGSMIME"],
        description: 'Recurso interno del INE para impugnar resoluciones emitidas por Consejos Locales o Distritales.',
        keywords: ["recurso revision INE","impugnar consejo distrital","recurso local INE"],
    },
    {
        id: 'elec-queja-infraccion-v1',
        slug: 'queja-infraccion-electoral-ine',
        title: 'Queja por Infraccion Electoral ante el INE',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/queja-infraccion-electoral-ine.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 441-465 LGIPE"],
        description: 'Queja para denunciar conductas que violan la normativa electoral como uso indebido de recursos publicos o propaganda.',
        keywords: ["queja electoral INE","denuncia infraccion partido","propaganda electoral ilegal"],
    },
    {
        id: 'elec-candidatura-independiente-v1',
        slug: 'solicitud-registro-candidatura-independiente',
        title: 'Solicitud de Registro de Candidatura Independiente',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/solicitud-registro-candidatura-independiente.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 357-387 LGIPE"],
        description: 'Tramite ante el INE para que un ciudadano se registre como candidato independiente a cargo de eleccion popular.',
        keywords: ["candidatura independiente INE","candidato sin partido","registro candidato ciudadano"],
    },
    {
        id: 'elec-acto-anticipado-v1',
        slug: 'queja-acto-anticipado-campana',
        title: 'Queja por Acto Anticipado de Campana Electoral',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/queja-acto-anticipado-campana.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 209, 449 Fr. I LGIPE"],
        description: 'Denuncia ante el INE por actos de precampana o campana anticipada antes del periodo legal autorizado.',
        keywords: ["acto anticipado campana","propaganda anticipada INE","queja precampana"],
    },
    {
        id: 'elec-queja-financiamiento-v1',
        slug: 'queja-financiamiento-ilegal-campana',
        title: 'Queja por Financiamiento Ilegal de Campana',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/queja-financiamiento-ilegal-campana.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 399-440 LGIPE"],
        description: 'Denuncia ante el INE por recepcion de financiamiento privado prohibido o rebase de topes de campana.',
        keywords: ["financiamiento ilegal campana","topes campana electoral","dinero sucio candidato"],
    },
    {
        id: 'elec-recuento-votos-v1',
        slug: 'solicitud-recuento-votos-casillas',
        title: 'Solicitud de Recuento de Votos en Casillas',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/solicitud-recuento-votos-casillas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 295-310 LGIPE"],
        description: 'Solicitud formal para que los computos distritales incluyan el recuento de ciertos paquetes electorales.',
        keywords: ["recuento votos casilla","recuento electoral","reconteo sufragios"],
    },
    {
        id: 'elec-denuncia-delito-v1',
        slug: 'denuncia-delito-electoral-fepade',
        title: 'Denuncia por Delito Electoral ante la FEPADE',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/denuncia-delito-electoral-fepade.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 401-413 CPEUM","Ley General en Materia de Delitos Electorales"],
        description: 'Denuncia formal ante la Fiscalia Especializada en Delitos Electorales por coaccion del voto, carrusel u otros delitos.',
        keywords: ["denuncia FEPADE","delito electoral","compra voto denuncia"],
    },
    {
        id: 'elec-convenio-coalicion-v1',
        slug: 'convenio-coalicion-partidos-politicos',
        title: 'Convenio de Coalicion entre Partidos Politicos',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/convenio-coalicion-partidos-politicos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 87-97 LGIPE"],
        description: 'Acuerdo formal entre dos o mas partidos para participar conjuntamente en una eleccion bajo plataforma comun.',
        keywords: ["coalicion partidos politicos","convenio alianza electoral","frente electoral Mexico"],
    },
    {
        id: 'elec-nombramiento-representante-v1',
        slug: 'nombramiento-representante-partido-casilla',
        title: 'Nombramiento de Representante de Partido ante Casilla',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/nombramiento-representante-partido-casilla.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 250-265 LGIPE"],
        description: 'Documento formal de un partido politico para designar a su representante ante una casilla electoral.',
        keywords: ["representante casilla partido","acreditacion partido electoral","fiscal de casilla"],
    },
    {
        id: 'elec-impugnacion-computo-v1',
        slug: 'escrito-impugnacion-computo-distrital',
        title: 'Escrito de Impugnacion del Computo Distrital',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/escrito-impugnacion-computo-distrital.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 291 Fr. I LGIPE"],
        description: 'Impugnacion formal de los computos realizados por el Consejo Distrital Electoral.',
        keywords: ["impugnar computo electoral","nulidad acta computo","protesta resultados distritales"],
    },
    {
        id: 'elec-acreditacion-observador-v1',
        slug: 'solicitud-acreditacion-observador-electoral',
        title: 'Solicitud de Acreditacion de Observadores Electorales',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/solicitud-acreditacion-observador-electoral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 217-228 LGIPE"],
        description: 'Registro de ciudadanos u organizaciones civiles como observadores electorales para la jornada.',
        keywords: ["observador electoral INE","acreditacion observador","civiles jornada electoral"],
    },
    {
        id: 'elec-reconsideracion-v1',
        slug: 'recurso-reconsideracion-tepjf',
        title: 'Recurso de Reconsideracion ante el TEPJF',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/recurso-reconsideracion-tepjf.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 61-66 LGSMIME"],
        description: 'Recurso extraordinario ante la Sala Superior del TEPJF para revisar sentencias de Salas Regionales.',
        keywords: ["reconsideracion TEPJF","Sala Superior electoral","recurso extraordinario electoral"],
    },
    {
        id: 'elec-impugnacion-consulta-v1',
        slug: 'impugnacion-resultado-consulta-popular',
        title: 'Impugnacion de Resultado de Consulta Popular',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/impugnacion-resultado-consulta-popular.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Consulta Popular","Art. 35 CPEUM"],
        description: 'Medio de impugnacion ante el TEPJF contra la validez del proceso de consulta popular.',
        keywords: ["consulta popular impugnacion","plebiscito Mexico TEPJF","resultado consulta ciudadana"],
    },
    {
        id: 'elec-queja-neutralidad-v1',
        slug: 'queja-neutralidad-gobierno-electoral',
        title: 'Queja por Violacion a la Neutralidad Gubernamental',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/queja-neutralidad-gobierno-electoral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 134 CPEUM","LGIPE Art. 449"],
        description: 'Denuncia contra servidor publico que usa recursos o cargo para favorecer a un candidato durante el proceso electoral.',
        keywords: ["neutralidad gobierno electoral","servidor publico propaganda","uso recursos publicos campana"],
    },
    {
        id: 'elec-nulidad-eleccion-v1',
        slug: 'demanda-nulidad-eleccion',
        title: 'Demanda de Nulidad de Eleccion',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/demanda-nulidad-eleccion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 53-78 LGSMIME"],
        description: 'Juicio ante el TEPJF para invalidar una eleccion por causas graves, determinantes y no reparables.',
        keywords: ["nulidad eleccion","anular gobernador","invalidar eleccion TEPJF"],
    },
    {
        id: 'elec-recurso-revocacion-mandato-v1',
        slug: 'impugnacion-proceso-revocacion-mandato',
        title: 'Impugnacion al Proceso de Revocacion de Mandato',
        specialty: 'electoral',
        tier: 'v1',
        file: 'v1/electoral/impugnacion-proceso-revocacion-mandato.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Revocacion de Mandato","Art. 35 Fr. IX CPEUM"],
        description: 'Medio de impugnacion ante el TEPJF contra irregularidades en el proceso de revocacion de mandato presidencial.',
        keywords: ["revocacion mandato impugnar","TEPJF revocacion","proceso revocacion electoral"],
    },
];
