
export const templatesV1_mercantil: Template[] = [
    {
        id: 'mercantil-demanda-ejecutiva-v1',
        slug: 'demanda-juicio-ejecutivo-mercantil',
        title: 'Demanda de Juicio Ejecutivo Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-juicio-ejecutivo-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1391-1415 Código de Comercio"],
        description: 'Cobro de título de crédito (pagaré, cheque, letra) mediante vía ejecutiva mercantil.',
        keywords: ["juicio ejecutivo mercantil","cobro pagaré","título de crédito"],
    },
    {
        id: 'mercantil-demanda-ordinaria-v1',
        slug: 'demanda-juicio-ordinario-mercantil',
        title: 'Demanda de Juicio Ordinario Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-juicio-ordinario-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1049-1063 Código de Comercio"],
        description: 'Reclamación de incumplimiento de contrato mercantil cuando no hay título ejecutivo.',
        keywords: ["juicio ordinario mercantil","contrato comercial incumplido","demanda compraventa"],
    },
    {
        id: 'mercantil-cobro-cheque-v1',
        slug: 'demanda-cobro-cheque-devuelto',
        title: 'Demanda de Cobro de Cheque Devuelto',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-cobro-cheque-devuelto.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 176-193 LGTOC","Arts. 1391 Código de Comercio"],
        description: 'Acción ejecutiva por cheque regresado por falta de fondos o defecto de firma.',
        keywords: ["cheque devuelto","cobro cheque sin fondos","titulo ejecutivo cheque"],
    },
    {
        id: 'mercantil-quiebra-v1',
        slug: 'solicitud-declaracion-quiebra',
        title: 'Solicitud de Declaración de Concurso Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/solicitud-declaracion-quiebra.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Concursos Mercantiles"],
        description: 'Petición al juez para iniciar el proceso de reorganización o quiebra de empresa en insolvencia.',
        keywords: ["concurso mercantil","quiebra empresa","insolvencia societaria"],
    },
    {
        id: 'mercantil-accion-cambiaria-v1',
        slug: 'demanda-accion-cambiaria-directa',
        title: 'Demanda de Acción Cambiaria Directa',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-accion-cambiaria-directa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 150-169 LGTOC"],
        description: 'Acción del tenedor de un título de crédito contra el obligado directo (aceptante o suscriptor).',
        keywords: ["acción cambiaria","letra de cambio","cobro cambiario pagaré"],
    },
    {
        id: 'mercantil-sociedad-disolucion-v1',
        slug: 'demanda-disolucion-sociedad-mercantil',
        title: 'Demanda de Disolución de Sociedad Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-disolucion-sociedad-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 229-241 LGSM"],
        description: 'Proceso judicial para declarar disuelta una SA o SRL cuando no se puede continuar operando.',
        keywords: ["disolución sociedad","disolver empresa SA","quórum sociedad mercantil"],
    },
    {
        id: 'mercantil-competencia-desleal-v1',
        slug: 'demanda-competencia-desleal',
        title: 'Demanda por Competencia Desleal',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-competencia-desleal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 6 bis, 10 bis Convenio de París","Ley Federal de Competencia Económica"],
        description: 'Acción por actos desleales como uso de marca similar, imitación de producto o difamación comercial.',
        keywords: ["competencia desleal","imitación marca","copia diseño comercial"],
    },
    {
        id: 'mercantil-medidas-cautelares-v1',
        slug: 'solicitud-medidas-cautelares-mercantiles',
        title: 'Solicitud de Medidas Cautelares Mercantiles',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/solicitud-medidas-cautelares-mercantiles.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1168-1177 Código de Comercio"],
        description: 'Aseguramiento de bienes o inhibitorias antes de juicio para garantizar el pago de la deuda.',
        keywords: ["embargo precautorio","aseguramiento bienes mercantil","inhibitoria mercantil"],
    },
    {
        id: 'mercantil-franquicia-incumplimiento-v1',
        slug: 'demanda-incumplimiento-contrato-franquicia',
        title: 'Demanda por Incumplimiento de Contrato de Franquicia',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-incumplimiento-contrato-franquicia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 142 Ley de Propiedad Industrial","Código de Comercio"],
        description: 'Acción contra franquiciante o franquiciatario por violación de cláusulas del contrato de franquicia.',
        keywords: ["franquicia incumplimiento","contrato franquicia","regalías franquicia"],
    },
    {
        id: 'mercantil-apelacion-v1',
        slug: 'recurso-apelacion-mercantil',
        title: 'Recurso de Apelación en Juicio Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/recurso-apelacion-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1336-1348 Código de Comercio"],
        description: 'Impugnación de sentencia de primera instancia ante el Tribunal Superior correspondiente.',
        keywords: ["apelación mercantil","segunda instancia mercantil","agravios apelación comercial"],
    },
    {
        id: 'mercantil-excepcion-compromiso-arbitral-v1',
        slug: 'excepcion-compromiso-arbitral',
        title: 'Excepción de Compromiso Arbitral',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/excepcion-compromiso-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1424 Código de Comercio","Ley de Arbitraje Comercial"],
        description: 'Defensa procesal para remitir el conflicto a arbitraje privado pactado en el contrato.',
        keywords: ["excepción arbitral","cláusula arbitraje","ICC arbitraje México"],
    },
    {
        id: 'mercantil-prenda-ejecucion-v1',
        slug: 'ejecucion-garantia-prendaria',
        title: 'Ejecución de Garantía Prendaria',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/ejecucion-garantia-prendaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 341-373 LGTOC"],
        description: 'Solicitud de remate extrajudicial o judicial de prenda otorgada como garantía de crédito incumplido.',
        keywords: ["ejecución prenda","remate garantía","crédito prendario"],
    },
    {
        id: 'mercantil-acciones-sociedad-v1',
        slug: 'demanda-reconocimiento-titularidad-acciones',
        title: 'Demanda de Reconocimiento de Titularidad de Acciones',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-reconocimiento-titularidad-acciones.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 111-140 LGSM"],
        description: 'Acción para que se declare la verdadera titularidad de acciones de una SA en conflicto societario.',
        keywords: ["acciones sociedad anónima","titulares acciones","derechos accionistas"],
    },
    {
        id: 'mercantil-responsabilidad-administrador-v1',
        slug: 'demanda-responsabilidad-administrador-sociedad',
        title: 'Demanda de Responsabilidad contra Administrador',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-responsabilidad-administrador-sociedad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 157-162 LGSM"],
        description: 'Acción de responsabilidad civil de los socios contra el administrador o consejo de administración por daños a la empresa.',
        keywords: ["responsabilidad administrador SA","daños consejo directivo","responsabilidad societaria"],
    },
    {
        id: 'mercantil-hipoteca-industrial-v1',
        slug: 'demanda-ejecucion-hipoteca-industrial',
        title: 'Demanda de Ejecución de Hipoteca Industrial',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-ejecucion-hipoteca-industrial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Títulos y Operaciones de Crédito","Arts. 1391 CC"],
        description: 'Ejecución de garantía hipotecaria sobre inmuebles o equipos de empresa deudora.',
        keywords: ["hipoteca industrial","ejecución hipotecaria empresa","crédito hipotecario incumplido"],
    },
    {
        id: 'mercantil-sociedades-hecho-v1',
        slug: 'demanda-liquidacion-sociedad-de-hecho',
        title: 'Demanda de Liquidación de Sociedad de Hecho',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-liquidacion-sociedad-de-hecho.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2688-2735 Código Civil Federal supletorio"],
        description: 'Cuando dos o más personas operaron comercialmente sin constituir formalmente una sociedad: se reclama la liquidación.',
        keywords: ["sociedad de hecho","liquidación sociedad irregular","negocios sin contrato"],
    },
    {
        id: 'mercantil-contrato-agencia-v1',
        slug: 'demanda-incumplimiento-contrato-agencia',
        title: 'Demanda por Incumplimiento de Contrato de Agencia',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-incumplimiento-contrato-agencia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 273-308 Código de Comercio"],
        description: 'Reclamación por omisión de comisiones, ruptura unilateral o competencia desleal por el agente o principal.',
        keywords: ["contrato agencia mercantil","agente comisionista","comisiones omitidas"],
    },
    {
        id: 'mercantil-contestacion-ejecutivo-v1',
        slug: 'contestacion-juicio-ejecutivo-mercantil',
        title: 'Contestación de Juicio Ejecutivo Mercantil',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/contestacion-juicio-ejecutivo-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1403 Código de Comercio"],
        description: 'Escrito de defensa del demandado negando el título, oponiendo excepciones o formulando reconvención.',
        keywords: ["contestar ejecutivo mercantil","excepciones pagaré","defensa título de crédito"],
    },
    {
        id: 'mercantil-venta-judicial-v1',
        slug: 'solicitud-venta-judicial-bienes-embargados',
        title: 'Solicitud de Venta Judicial de Bienes Embargados',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/solicitud-venta-judicial-bienes-embargados.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1411-1414 Código de Comercio"],
        description: 'Petición de remate judicial de los bienes embargados durante la ejecución de sentencia mercantil.',
        keywords: ["remate judicial mercantil","venta bienes embargados","liquidación embargo"],
    },
    {
        id: 'mercantil-contrato-suministro-v1',
        slug: 'demanda-incumplimiento-contrato-suministro',
        title: 'Demanda por Incumplimiento de Contrato de Suministro',
        specialty: 'mercantil',
        tier: 'v1',
        file: 'v1/mercantil/demanda-incumplimiento-contrato-suministro.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 304-310 Codigo de Comercio"],
        description: 'Reclamacion cuando el proveedor no entrega la mercancia en tiempo o calidad pactada.',
        keywords: ["suministro mercantil","proveedor incumplido","entrega mercancia"],
    },
];
