
export const templatesV1_familiar: Template[] = [
    {
        id: 'familiar-divorcio-incausado-v1',
        slug: 'demanda-divorcio-incausado',
        title: 'Demanda de Divorcio Incausado',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-divorcio-incausado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 266 CCDF"],
        description: 'Divorcio sin necesidad de expresar causa ante Juez Familiar.',
        keywords: ["divorcio incausado","separación matrimonial","pensión alimenticia"],
    },
    {
        id: 'familiar-pension-alimenticia-v1',
        slug: 'demanda-pension-alimenticia',
        title: 'Demanda de Pensión Alimenticia',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-pension-alimenticia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 301-323 CCDF"],
        description: 'Fijación judicial de alimentos para menores o cónyuge por incumplimiento voluntario.',
        keywords: ["pensión alimenticia","alimentos menores","obligación alimentaria"],
    },
    {
        id: 'familiar-guarda-custodia-v1',
        slug: 'demanda-guarda-custodia-menores',
        title: 'Demanda de Guarda y Custodia',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-guarda-custodia-menores.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 282-283 CCDF","Arts. 414-416 Bis CCDF"],
        description: 'Asignación judicial de custodia de menores en proceso de divorcio o separación.',
        keywords: ["guarda custodia","menores divorcio","patria potestad"],
    },
    {
        id: 'familiar-visitas-v1',
        slug: 'demanda-regimen-visitas',
        title: 'Demanda de Régimen de Visitas',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-regimen-visitas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 416 Ter CCDF"],
        description: 'Establecimiento judicial del derecho de convivencia entre padre no custodio e hijos.',
        keywords: ["régimen visitas","convivencia menores","padre no custodio"],
    },
    {
        id: 'familiar-aumento-pension-v1',
        slug: 'demanda-aumento-pension-alimenticia',
        title: 'Demanda de Aumento de Pensión Alimenticia',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-aumento-pension-alimenticia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 311 CCDF"],
        description: 'Incremento de la pensión cuando han aumentado las necesidades de los acreedores o los ingresos del deudor.',
        keywords: ["aumento pensión alimentos","más pensión","revisión alimentos"],
    },
    {
        id: 'familiar-adopcion-v1',
        slug: 'solicitud-adopcion-plena',
        title: 'Solicitud de Adopción Plena',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/solicitud-adopcion-plena.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 390-410 CCDF"],
        description: 'Proceso judicial para adoptar a un menor bajo tutela del DIF con plenos efectos de filiación.',
        keywords: ["adopción plena","adoptar menor DIF","filiación adoptiva"],
    },
    {
        id: 'familiar-patria-potestad-v1',
        slug: 'demanda-perdida-patria-potestad',
        title: 'Demanda de Pérdida de Patria Potestad',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-perdida-patria-potestad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 444 CCDF"],
        description: 'Privación judicial de la patria potestad por abandono, violencia o delito grave del progenitor.',
        keywords: ["pérdida patria potestad","abandono menores","violencia progenitor"],
    },
    {
        id: 'familiar-declaracion-maternidad-v1',
        slug: 'demanda-reconocimiento-filiacion',
        title: 'Demanda de Reconocimiento de Filiación',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-reconocimiento-filiacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 340-381 CCDF"],
        description: 'Acción para que el padre reconozca judicialmente al hijo no inscrito o confirmación por prueba de ADN.',
        keywords: ["reconocimiento filiación","paternidad judicial","ADN inscripción"],
    },
    {
        id: 'familiar-violencia-medidas-v1',
        slug: 'solicitud-medidas-proteccion-violencia',
        title: 'Solicitud de Medidas de Protección por Violencia Familiar',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/solicitud-medidas-proteccion-violencia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Acceso de las Mujeres a una Vida Libre de Violencia","Art. 282 CCDF"],
        description: 'Órdenes de protección urgentes ante el Juez Familiar o el Ministerio Público.',
        keywords: ["medidas protección violencia","orden alejamiento","violencia familiar"],
    },
    {
        id: 'familiar-intestamentario-familiar-v1',
        slug: 'demanda-sucesion-familiar-intestamentaria',
        title: 'Juicio Sucesorio Intestamentario Familiar',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-sucesion-familiar-intestamentaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1599-1668 CCDF"],
        description: 'Tramitación ante Juez Familiar de la herencia cuando no hay testamento.',
        keywords: ["sucesión familiar intestamentaria","herederos sin testamento","albacea familiar"],
    },
    {
        id: 'familiar-convenio-divorcio-v1',
        slug: 'convenio-regulador-divorcio',
        title: 'Convenio Regulador de Divorcio',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/convenio-regulador-divorcio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 267 CCDF"],
        description: 'Acuerdo sobre guarda, alimentos, visitas y bienes que ambos cónyuges presentan al Juez.',
        keywords: ["convenio divorcio","acuerdo pensión","bienes divorciados"],
    },
    {
        id: 'familiar-tutela-menor-v1',
        slug: 'solicitud-tutela-menor-orfano',
        title: 'Solicitud de Tutela de Menor Huérfano',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/solicitud-tutela-menor-orfano.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 462-543 CCDF"],
        description: 'Nombramiento judicial de tutor para menor cuyos padres han fallecido o fueron privados de la patria potestad.',
        keywords: ["tutor menor","huérfano tutela","menor desprotegido"],
    },
    {
        id: 'familiar-interdiccion-v1',
        slug: 'demanda-declaracion-interdiccion',
        title: 'Demanda de Declaración de Interdicción',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-declaracion-interdiccion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 450-466 CCDF"],
        description: 'Proceso para declarar incapaz a un mayor de edad por trastorno mental permanente.',
        keywords: ["interdicción adulto","incapacidad civil","curador juridico"],
    },
    {
        id: 'familiar-alimentos-mayores-v1',
        slug: 'demanda-alimentos-ascendientes',
        title: 'Demanda de Alimentos para Ascendientes',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-alimentos-ascendientes.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 301-323 CCDF"],
        description: 'Pensión alimenticia de hijos adultos hacia padres en situación de vulnerabilidad.',
        keywords: ["alimentos padres","pensión ascendientes","adultos mayores alimentación"],
    },
    {
        id: 'familiar-divorcio-necesario-v1',
        slug: 'demanda-divorcio-causas-graves',
        title: 'Demanda de Separación por Causas Graves (Div. Necesario)',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-divorcio-causas-graves.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 267 CCDF (causales históricas) / Legislación Estatal"],
        description: 'Estados que aún conservan el divorcio necesario, listando causas específicas como adulterio o violencia.',
        keywords: ["divorcio necesario","causa divorcio","adulterio divorcio estatal"],
    },
    {
        id: 'familiar-solicitud-antecedentes-v1',
        slug: 'solicitud-acta-de-nacimiento-rectificacion',
        title: 'Rectificación de Acta de Nacimiento',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/solicitud-acta-de-nacimiento-rectificacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 134-139 CCDF"],
        description: 'Corrección de errores materiales en acta de nacimiento (nombre, fechas, parentesco) ante Juez Familiar.',
        keywords: ["rectificación acta nacimiento","error acta civil","corrección nombre registro"],
    },
    {
        id: 'familiar-impugnacion-paternidad-v1',
        slug: 'demanda-impugnacion-paternidad',
        title: 'Demanda de Impugnación de Paternidad',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-impugnacion-paternidad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 329-334 CCDF"],
        description: 'Acción del marido o terceros para destruir la presunción de paternidad sobre un hijo inscrito.',
        keywords: ["impugnación paternidad","negar paternidad","hijo no biológico"],
    },
    {
        id: 'familiar-alimentos-provisionales-v1',
        slug: 'solicitud-alimentos-provisionales',
        title: 'Solicitud de Alimentos Provisionales',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/solicitud-alimentos-provisionales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 282 Fracc. XIV CCDF"],
        description: 'Petición urgente de pensión provisional mientras se tramita el juicio principal de alimentos.',
        keywords: ["alimentos provisionales urgentes","pensión temporal","medidas cautelares alimentos"],
    },
    {
        id: 'familiar-reduccion-pension-v1',
        slug: 'demanda-reduccion-pension-alimenticia',
        title: 'Demanda de Reducción de Pensión Alimenticia',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-reduccion-pension-alimenticia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 311 CCDF"],
        description: 'Solicitud del deudor para bajar la pensión cuando han disminuido sus ingresos o aumentado sus cargas.',
        keywords: ["reducción alimentos","bajar pensión","cambio circunstancias"],
    },
    {
        id: 'familiar-reduccion-pension-v1',
        slug: 'demanda-reduccion-pension-alimenticia',
        title: 'Demanda de Reduccion de Pension Alimenticia',
        specialty: 'familiar',
        tier: 'v1',
        file: 'v1/familiar/demanda-reduccion-pension-alimenticia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 311 CCDF"],
        description: 'Solicitud del deudor para bajar la pension cuando disminuyen sus ingresos o aumentan cargas.',
        keywords: ["reduccion alimentos","bajar pension","cambio circunstancias alimentarias"],
    },
];
