
export const templatesV1_internacional: Template[] = [
    {
        id: 'intl-contrato-compraventa-internacional-v1',
        slug: 'contrato-compraventa-internacional-mercancias',
        title: 'Contrato de Compraventa Internacional de Mercancías',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-compraventa-internacional-mercancias.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convención de Viena CISG 1980","Incoterms 2020"],
        description: 'Contrato de exportación/importación de mercancías con cláusulas de Incoterms, ley aplicable y arbitraje.',
        keywords: ["compraventa internacional","contrato exportacion","CISG Incoterms"],
    },
    {
        id: 'intl-carta-rogotaria-v1',
        slug: 'carta-rogatoria-international',
        title: 'Carta Rogatoria Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/carta-rogatoria-international.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 17 CPEUM","Convención Interamericana sobre Exhortos"],
        description: 'Solicitud de cooperación judicial entre tribunales de distintos países para practicar diligencias.',
        keywords: ["carta rogatoria internacional","exhorto internacional","cooperacion judicial CIDIP"],
    },
    {
        id: 'intl-contrato-agencia-exportacion-v1',
        slug: 'contrato-agencia-exportacion-distribucion',
        title: 'Contrato de Agencia para Exportación y Distribución',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-agencia-exportacion-distribucion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG","Código de Comercio México"],
        description: 'Acuerdo de distribución para que un agente extranjero comercialice productos mexicanos en su país.',
        keywords: ["agencia exportacion contrato","distribucion internacional","agente exclusivo extranjero"],
    },
    {
        id: 'intl-reconocimiento-sentencia-extranjera-v1',
        slug: 'solicitud-reconocimiento-sentencia-extranjera',
        title: 'Solicitud de Reconocimiento de Sentencia Extranjera (Exequátur)',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/solicitud-reconocimiento-sentencia-extranjera.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 569-577 CFPC","Convención de Panamá 1975"],
        description: 'Proceso ante juez mexicano para dar eficacia a una sentencia dictada en otro país.',
        keywords: ["homologacion sentencia extranjera","exequatur Mexico","reconocimiento fallo extranjero"],
    },
    {
        id: 'intl-clausula-arbitraje-v1',
        slug: 'clausula-arbitraje-internacional',
        title: 'Cláusula de Arbitraje Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/clausula-arbitraje-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG Art. 6","Reglamento ICC 2021"],
        description: 'Cláusula contractual que somete las controversias al arbitraje internacional bajo reglas ICC, UNCITRAL o CAM.',
        keywords: ["clausula arbitraje ICC","arbitraje internacional contrato","disputas internacionales"],
    },
    {
        id: 'intl-contrato-joint-venture-v1',
        slug: 'contrato-joint-venture-internacional',
        title: 'Contrato de Joint Venture Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-joint-venture-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG","Ley de Inversión Extranjera"],
        description: 'Acuerdo de empresa conjunta entre socios de distintos países para explotar un negocio en México o en el extranjero.',
        keywords: ["joint venture internacional","asociacion empresas extranjeras","inversion extranjera Mexico"],
    },
    {
        id: 'intl-carta-credito-v1',
        slug: 'apertura-carta-credito-documentaria',
        title: 'Apertura de Carta de Crédito Documentaria',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/apertura-carta-credito-documentaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["UCP 600 CCI","LGTOC Art. 290-307"],
        description: 'Instrucción bancaria para abrir una carta de crédito que garantiza el pago internacional al exportador.',
        keywords: ["carta de credito LC","UCP 600","pago internacional documentario"],
    },
    {
        id: 'intl-poder-notarial-extranjero-v1',
        slug: 'poder-notarial-uso-extranjero',
        title: 'Poder Notarial para Uso en el Extranjero',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/poder-notarial-uso-extranjero.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convenio de La Haya","Ley del Notariado CDMX"],
        description: 'Poder otorgado ante Notario mexicano, con apostille, para surtir efectos legales en otro país.',
        keywords: ["poder notarial extranjero","apostille poder","mandato uso internacional"],
    },
    {
        id: 'intl-contrato-prestacion-servicios-v1',
        slug: 'contrato-prestacion-servicios-internacional',
        title: 'Contrato de Prestación de Servicios Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-prestacion-servicios-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG Art. 1","Código de Comercio México"],
        description: 'Acuerdo internacional por el cual una empresa mexicana presta servicios a un cliente extranjero.',
        keywords: ["contrato servicios internacional","outsourcing Mexico","prestacion servicios exportacion"],
    },
    {
        id: 'intl-convenio-doble-tributacion-v1',
        slug: 'solicitud-beneficios-convenio-doble-tributacion',
        title: 'Solicitud de Beneficios por Convenio de Doble Tributación',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/solicitud-beneficios-convenio-doble-tributacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Tratado MX-EUA para Evitar la Doble Imposición","Art. 4 LISR"],
        description: 'Escrito para solicitar la aplicación del CDT entre México y otro país para evitar pagar impuesto doble.',
        keywords: ["convenio doble tributacion","CDT Mexico","beneficios tratado fiscal"],
    },
    {
        id: 'intl-demanda-arbitraje-ciadi-v1',
        slug: 'demanda-arbitraje-ciadi-inversion',
        title: 'Demanda de Arbitraje ante el CIADI',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/demanda-arbitraje-ciadi-inversion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convenio CIADI","T-MEC Capítulo 11"],
        description: 'Demanda internacional de un inversionista extranjero contra el Estado mexicano por violación del T-MEC.',
        keywords: ["CIADI demanda","inversionista Estado TMEC","arbitraje inversion extranjera"],
    },
    {
        id: 'intl-acuerdo-confidencialidad-internacional-v1',
        slug: 'acuerdo-confidencialidad-internacional',
        title: 'Acuerdo de Confidencialidad Internacional (NDA Cross-Border)',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/acuerdo-confidencialidad-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG","GDPR si aplica","LFPDPPP"],
        description: 'NDA binacional para proteger información entre empresas de distintos países durante negociaciones.',
        keywords: ["NDA internacional","confidencialidad bilateral","acuerdo secreto empresas extranjeras"],
    },
    {
        id: 'intl-tm-ec-origen-v1',
        slug: 'certificado-origen-t-mec',
        title: 'Certificado de Origen T-MEC',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/certificado-origen-t-mec.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["T-MEC Capítulo 5","Reglas de Origen Específicas"],
        description: 'Declaración del exportador certificando que la mercancía cumple las reglas de origen del T-MEC para acceder a preferencias arancelarias.',
        keywords: ["certificado origen TMEC","reglas origen Mexico","USMCA certificate of origin"],
    },
    {
        id: 'intl-demanda-incumplimiento-contrato-v1',
        slug: 'demanda-incumplimiento-contrato-internacional',
        title: 'Demanda por Incumplimiento de Contrato Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/demanda-incumplimiento-contrato-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG Art. 45-52","Código de Comercio"],
        description: 'Acción ante tribunal o árbitro internacional por incumplimiento de obligaciones contractuales entre empresas de distintos países.',
        keywords: ["incumplimiento contrato internacional","demanda CISG","proveedor extranjero incumple"],
    },
    {
        id: 'intl-solicitud-extradicion-v1',
        slug: 'solicitud-extradicion-internacional',
        title: 'Solicitud de Extradición Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/solicitud-extradicion-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 10-22 Ley de Extradición","Tratados Bilaterales de Extradición"],
        description: 'Solicitud formal del Estado Mexicano a otro país para que entregue a un individuo acusado de delito.',
        keywords: ["extradicion Mexico","solicitud extradicion prófugo","tratado extradicion bilateral"],
    },
    {
        id: 'intl-contrato-franquicia-internacional-v1',
        slug: 'contrato-franquicia-internacional',
        title: 'Contrato de Franquicia Internacional (Master Franchise)',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-franquicia-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 142 Ley de Propiedad Industrial","Código de Comercio"],
        description: 'Acuerdo que otorga a un franquiciatario extranjero la subfranquicia maestra para operar en su territorio.',
        keywords: ["franquicia internacional","master franchise","subfranquicia extranjero"],
    },
    {
        id: 'intl-protecion-inversion-extranjera-v1',
        slug: 'aviso-inversion-extranjera-cnie',
        title: 'Aviso de Inversión Extranjera ante la CNIE',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/aviso-inversion-extranjera-cnie.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 7-17 Ley de Inversión Extranjera"],
        description: 'Notificación obligatoria a la CNIE cuando una empresa extranjera adquiere participación en empresa mexicana.',
        keywords: ["inversion extranjera CNIE","aviso adquisicion empresa","autorización inversion extranjera"],
    },
    {
        id: 'intl-pedimento-aduanal-v1',
        slug: 'pedimento-importacion-aduanal',
        title: 'Pedimento de Importación Aduanal',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/pedimento-importacion-aduanal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 36-43 Ley Aduanera","Art. 73 Ley Aduanera"],
        description: 'Declaración aduanera formal para ingresar mercancías a territorio mexicano cumpliendo requisitos arancelarios.',
        keywords: ["pedimento importacion","aduana Mexico despacho","importar mercancias pedimento"],
    },
    {
        id: 'intl-contrato-licencia-tecnologia-internacional-v1',
        slug: 'contrato-licencia-tecnologia-internacional',
        title: 'Contrato de Licencia Tecnológica Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/contrato-licencia-tecnologia-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CISG","Arts. 145-163 Ley de Propiedad Industrial"],
        description: 'Acuerdo por el que una empresa extranjera licencia su tecnología patentada a una empresa mexicana.',
        keywords: ["licencia tecnologia internacional","patente extranjera contrato","tecnologia licencia cross-border"],
    },
    {
        id: 'intl-convenio-cooperacion-v1',
        slug: 'convenio-cooperacion-institucional-internacional',
        title: 'Convenio de Cooperación Institucional Internacional',
        specialty: 'internacional',
        tier: 'v1',
        file: 'v1/internacional/convenio-cooperacion-institucional-internacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convención de Viena sobre el Derecho de los Tratados"],
        description: 'Acuerdo de cooperación entre instituciones mexicanas y extranjeras para proyectos conjuntos educativos, científicos o comerciales.',
        keywords: ["convenio cooperacion institucional","acuerdo interinstitucional internacional","MOU Mexico"],
    },
];
