
export const templatesV1_penal: Template[] = [
    {
        id: 'penal-denuncia-robo-v1',
        slug: 'denuncia-penal-robo',
        title: 'Denuncia Penal por Robo',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/denuncia-penal-robo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 220-224 CPDF","Arts. 379-394 CPF"],
        description: 'Denuncia formal ante MP por sustracción de bienes sin violencia (robo simple) o con violencia.',
        keywords: ["denuncia robo","robo simple","robo con violencia","MP denuncia"],
    },
    {
        id: 'penal-querella-fraude-v1',
        slug: 'querella-fraude',
        title: 'Querella por Fraude',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/querella-fraude.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 386-389 CPF","Art. 230 CPDF"],
        description: 'Querella por engaño que causó transferencia patrimonial ilícita en perjuicio del ofendido.',
        keywords: ["querella fraude","engaño dinero","víctima fraude penal"],
    },
    {
        id: 'penal-denuncia-violencia-familiar-v1',
        slug: 'denuncia-violencia-familiar',
        title: 'Denuncia por Violencia Familiar',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/denuncia-violencia-familiar.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 200-204 CPDF","Ley General de Acceso a una Vida Libre de Violencia"],
        description: 'Denuncia por actos de violencia física, psicológica, económica o sexual dentro del núcleo familiar.',
        keywords: ["violencia familiar denuncia","maltrato familiar","agresión doméstica"],
    },
    {
        id: 'penal-escrito-ofendido-v1',
        slug: 'escrito-victima-ofendido-coadyuvancia',
        title: 'Escrito de Coadyuvancia de la Víctima',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/escrito-victima-ofendido-coadyuvancia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 109, 110 CNPP"],
        description: 'Escrito mediante el cual la víctima o el ofendido coadyuva con el Ministerio Público en la carpeta de investigación.',
        keywords: ["coadyuvancia víctima","ofendido penal","pruebas víctima carpeta"],
    },
    {
        id: 'penal-solicitud-no-ejercicio-accion-v1',
        slug: 'impugnacion-no-ejercicio-accion-penal',
        title: 'Impugnación de No Ejercicio de la Acción Penal',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/impugnacion-no-ejercicio-accion-penal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 258 CNPP"],
        description: 'Recurso cuando el MP determina el no ejercicio de la acción penal y la víctima lo impugna ante el Fiscal Superior.',
        keywords: ["impugnar MP no ejercicio","recurso no ejercicio acción","fiscal superior nep"],
    },
    {
        id: 'penal-escrito-defensa-imputado-v1',
        slug: 'escrito-defensa-al-imputado',
        title: 'Escrito de Defensa del Imputado',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/escrito-defensa-al-imputado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 113, 117 CNPP"],
        description: 'Comunicación formal del defensor solicitando diligencias, impugnando actuaciones o solicitando copias en la etapa de investigación.',
        keywords: ["escrito defensa imputado","carpeta investigación defensor","diligencias defensa"],
    },
    {
        id: 'penal-solicitud-libertad-cautelar-v1',
        slug: 'solicitud-sustitucion-medida-cautelar',
        title: 'Solicitud de Sustitución de Medida Cautelar',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-sustitucion-medida-cautelar.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 153-177 CNPP"],
        description: 'Petición al Juez de Control para sustituir la prisión preventiva por una medida menos gravosa.',
        keywords: ["sustitucion prisión preventiva","medida cautelar alternativa","libertad cautelar"],
    },
    {
        id: 'penal-acuerdo-reparatorio-v1',
        slug: 'solicitud-acuerdo-reparatorio',
        title: 'Solicitud de Acuerdo Reparatorio',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-acuerdo-reparatorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 186-191 CNPP"],
        description: 'Mecanismo alternativo de solución de controversias en delitos que admiten acuerdos reparatorios.',
        keywords: ["acuerdo reparatorio penal","salida alterna delitos","reparación daño acordada"],
    },
    {
        id: 'penal-suspension-condicional-v1',
        slug: 'solicitud-suspension-condicional-proceso',
        title: 'Solicitud de Suspensión Condicional del Proceso',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-suspension-condicional-proceso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 192-198 CNPP"],
        description: 'Salida alterna que suspende el proceso penal si el imputado cumple condiciones fijadas por el Juez por cierto tiempo.',
        keywords: ["suspensión condicional proceso","salida alterna penal","probación penal"],
    },
    {
        id: 'penal-procedimiento-abreviado-v1',
        slug: 'solicitud-procedimiento-abreviado',
        title: 'Solicitud de Procedimiento Abreviado',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-procedimiento-abreviado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 201-207 CNPP"],
        description: 'El imputado se declara culpable a cambio de una pena reducida, evitando juicio oral.',
        keywords: ["procedimiento abreviado","plea deal México","reducción pena acuerdo"],
    },
    {
        id: 'penal-querella-abuso-confianza-v1',
        slug: 'querella-abuso-de-confianza',
        title: 'Querella por Abuso de Confianza',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/querella-abuso-de-confianza.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 228 CPDF","Arts. 382-386 CPF"],
        description: 'Querella contra quien recibió bienes en depósito, comisión o administración y los dispone en beneficio propio.',
        keywords: ["abuso confianza penal","apropiación indebida","dedepositario infiel"],
    },
    {
        id: 'penal-incidente-incompetencia-v1',
        slug: 'excepcion-incompetencia-penal',
        title: 'Excepción de Incompetencia en Materia Penal',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/excepcion-incompetencia-penal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 30-38 CNPP"],
        description: 'Escrito del defensor planteando que el Juez de Control que conoce no es competente por territorio o materia.',
        keywords: ["incompetencia penal","excepción jurisdicción penal","declinación competencia"],
    },
    {
        id: 'penal-recurso-apelacion-v1',
        slug: 'recurso-apelacion-penal',
        title: 'Recurso de Apelación Penal',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/recurso-apelacion-penal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 467-484 CNPP"],
        description: 'Medio de impugnación contra resoluciones del Juez de Control, como la vinculación a proceso o las medidas cautelares.',
        keywords: ["apelación penal","impugnar vinculación proceso","recurso acusatorio"],
    },
    {
        id: 'penal-ampliacion-denuncia-v1',
        slug: 'ampliacion-denuncia-penal',
        title: 'Ampliación de Denuncia Penal',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/ampliacion-denuncia-penal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 222 CNPP"],
        description: 'Documento adicional que amplía o complementa la denuncia inicial con nuevos hechos o datos de prueba.',
        keywords: ["ampliacion denuncia","nuevos datos denuncia","complementar carpeta"],
    },
    {
        id: 'penal-denuncia-extorsion-v1',
        slug: 'denuncia-extorsion',
        title: 'Denuncia por Extorsión',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/denuncia-extorsion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 390 CPF","Art. 236 CPDF"],
        description: 'Denuncia penal por exigencia de dinero bajo amenaza de causar daño a la persona o sus bienes.',
        keywords: ["extorsion denuncia","cobro piso","amenazas dinero"],
    },
    {
        id: 'penal-solicitud-reparacion-daño-v1',
        slug: 'solicitud-reparacion-dano-victima',
        title: 'Solicitud de Reparación del Daño (Víctima)',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-reparacion-dano-victima.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 109 Fr. VII CNPP","Arts. 29-38 CPF"],
        description: 'Petición formal de la víctima ante el Juez para que en la sentencia se condene al acusado a reparar el daño causado.',
        keywords: ["reparación del daño víctima","condena reparar daño","sentencia daños penales"],
    },
    {
        id: 'penal-denuncia-delitos-informaticos-v1',
        slug: 'denuncia-delitos-informaticos',
        title: 'Denuncia por Delito Informático',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/denuncia-delitos-informaticos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 211 bis 1-7 CPF","Ley Federal de Datos Personales"],
        description: 'Denuncia por hackeo, phishing, suplantación de identidad digital o robo de datos personales.',
        keywords: ["delito informático denuncia","hackeo computadora","phishing cibercriminal"],
    },
    {
        id: 'penal-solicitud-orden-aprehension-v1',
        slug: 'solicitud-orden-aprehension-mp',
        title: 'Escrito del MP Solicitando Orden de Aprehensión',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-orden-aprehension-mp.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 141 CNPP","Art. 16 CPEUM"],
        description: 'Solicitud formal del Ministerio Público al Juez de Control para librar una orden de captura.',
        keywords: ["orden aprehensión MP","solicitud captura juez","control penal"],
    },
    {
        id: 'penal-denuncia-lesiones-v1',
        slug: 'denuncia-lesiones-fisicas',
        title: 'Denuncia por Lesiones',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/denuncia-lesiones-fisicas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 288-301 CPF","Arts. 130-133 CPDF"],
        description: 'Denuncia por daños corporales causados por otro con o sin arma, acreditados con certificado médico.',
        keywords: ["denuncia lesiones","golpes certificado médico","lesiones dolosas"],
    },
    {
        id: 'penal-medida-proteccion-mp-v1',
        slug: 'solicitud-medida-proteccion-urgente',
        title: 'Solicitud de Medida de Proteccion Urgente al MP',
        specialty: 'penal',
        tier: 'v1',
        file: 'v1/penal/solicitud-medida-proteccion-urgente.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 137-138 CNPP","Ley General de Victimas Art. 27"],
        description: 'Peticion de medidas de proteccion provisionales que dicta el MP antes de acudir al Juez.',
        keywords: ["medida proteccion ministerio publico","proteccion victima urgente","MP orden proteccion"],
    },
];
