
export const templatesV1_administrativo: Template[] = [
    {
        id: 'admin-derecho-peticion-v1',
        slug: 'escrito-derecho-peticion',
        title: 'Escrito de Petición (Art. 8 Constitucional)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/escrito-derecho-peticion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 8 CPEUM","Arts. 1, 15 LFPA"],
        description: 'Escrito formal para ejercer el derecho de petición ante cualquier autoridad administrativa.',
        keywords: ["derecho de petición","escrito libre","oficio autoridad","artículo 8 constitucional"],
    },
    {
        id: 'admin-recurso-revision-v1',
        slug: 'recurso-revision-lfpa',
        title: 'Recurso de Revisión Administrativa (LFPA)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-revision-lfpa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 83-96 LFPA"],
        description: 'Recurso de revisión contra actos de autoridades de la Administración Pública Federal.',
        keywords: ["recurso de revisión","lfpa","impugnación administrativa"],
    },
    {
        id: 'admin-recurso-inconformidad-v1',
        slug: 'recurso-inconformidad',
        title: 'Recurso de Inconformidad',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-inconformidad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público"],
        description: 'Recurso contra fallos en procedimientos de licitación pública.',
        keywords: ["inconformidad","licitación pública","LAASSP"],
    },
    {
        id: 'admin-nulidad-federal-v1',
        slug: 'juicio-nulidad-federal',
        title: 'Demanda de Juicio de Nulidad Federal',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/juicio-nulidad-federal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Procedimiento Contencioso Administrativo"],
        description: 'Demanda de nulidad ante el Tribunal Federal de Justicia Administrativa (TFJA).',
        keywords: ["juicio de nulidad","tfja","contencioso administrativo"],
    },
    {
        id: 'admin-queja-servidor-publico-v1',
        slug: 'queja-servidor-publico',
        title: 'Queja contra Servidor Público',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/queja-servidor-publico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Responsabilidades Administrativas"],
        description: 'Denuncia por faltas administrativas u omisiones de servidores públicos ante OIC.',
        keywords: ["queja","servidor público","OIC","responsabilidad administrativa"],
    },
    {
        id: 'admin-licencia-funcionamiento-v1',
        slug: 'solicitud-licencia-funcionamiento',
        title: 'Solicitud de Licencia de Funcionamiento',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/solicitud-licencia-funcionamiento.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Establecimientos Mercantiles"],
        description: 'Formato libre de solicitud para apertura y funcionamiento de establecimientos.',
        keywords: ["licencia de funcionamiento","apertura negocio","aviso mercantil"],
    },
    {
        id: 'admin-contestacion-requerimiento-v1',
        slug: 'contestacion-requerimiento-autoridad',
        title: 'Contestación a Requerimiento Administrativo',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/contestacion-requerimiento-autoridad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 8 CPEUM","Arts. 1, 15 LFPA"],
        description: 'Escrito de desahogo y cumplimiento a requerimientos formulados por la autoridad.',
        keywords: ["contestación","requerimiento","desahogo de vista"],
    },
    {
        id: 'admin-solicitud-inai-v1',
        slug: 'solicitud-informacion-publica-inai',
        title: 'Solicitud de Acceso a la Información (Transparencia)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/solicitud-informacion-publica-inai.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Transparencia y Acceso a la Información Pública"],
        description: 'Formato libre para solicitar información pública gubernamental sin necesidad de interés jurídico.',
        keywords: ["transparencia","información pública","INAI","PNT"],
    },
    {
        id: 'admin-recurso-revision-transparencia-v1',
        slug: 'recurso-revision-transparencia',
        title: 'Recurso de Revisión en Transparencia',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-revision-transparencia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Transparencia Art. 142"],
        description: 'Impugnación por negativa de información o información incompleta por parte del Sujeto Obligado.',
        keywords: ["INAI","recurso revisión transparencia","información oculta"],
    },
    {
        id: 'admin-alegatos-procedimiento-v1',
        slug: 'alegatos-procedimiento-administrativo',
        title: 'Alegatos en Procedimiento Administrativo',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/alegatos-procedimiento-administrativo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 39 LFPA"],
        description: 'Escrito final de alegatos previo a que la autoridad dicte resolución administrativa.',
        keywords: ["alegatos administrativos","cierre de instrucción","LFPA"],
    },
    {
        id: 'admin-revocacion-admin-v1',
        slug: 'recurso-revocacion-administrativa',
        title: 'Recurso de Revocación Administrativa',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-revocacion-administrativa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Procedimiento Administrativo Local"],
        description: 'Recurso ordinario contra actos de autoridades estatales o municipales (clausuras, retenciones).',
        keywords: ["revocación administrativa","impugnación municipal","multa municipal"],
    },
    {
        id: 'admin-responsabilidad-patrimonial-v1',
        slug: 'demanda-responsabilidad-patrimonial-estado',
        title: 'Demanda de Responsabilidad Patrimonial del Estado',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/demanda-responsabilidad-patrimonial-estado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Responsabilidad Patrimonial del Estado","Art. 109 Constitucional"],
        description: 'Ramo administrativo. Indemnización por daños causados por actividad administrativa irregular.',
        keywords: ["responsabilidad patrimonial","indemnización estado","negligencia médica pública","bache daño auto"],
    },
    {
        id: 'admin-uso-suelo-v1',
        slug: 'solicitud-dictamen-uso-suelo',
        title: 'Solicitud de Dictamen de Uso de Suelo',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/solicitud-dictamen-uso-suelo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Leyes de Desarrollo Urbano Locales"],
        description: 'Petición para obtener factibilidad o dictamen de uso de suelo comercial o industrial.',
        keywords: ["uso de suelo","desarrollo urbano","factibilidad comercial"],
    },
    {
        id: 'admin-suspension-administrativa-v1',
        slug: 'escrito-suspension-acto-reclamado-administrativo',
        title: 'Solicitud de Suspensión del Acto en Recurso Administrativo',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/escrito-suspension-acto-reclamado-administrativo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 87 LFPA"],
        description: 'Petición incidental dentro de un recurso para que no se ejecute una clausura o multa.',
        keywords: ["suspensión","medida cautelar","paralización de clausura","LFPA"],
    },
    {
        id: 'admin-reclamacion-administrativa-v1',
        slug: 'recurso-reclamacion-administrativo',
        title: 'Recurso de Reclamación (Contra Acuerdos de Trámite)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-reclamacion-administrativo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Procedimiento Contencioso Administrativo"],
        description: 'Impugnación dentro del Tribunal Contencioso contra acuerdos del Magistrado Instructor que desechan pruebas o demandas.',
        keywords: ["reclamación tfja","acuerdo desechamiento","magistrado instructor"],
    },
    {
        id: 'admin-contestacion-procedimiento-sancionador-v1',
        slug: 'contestacion-procedimiento-administrativo-sancionador',
        title: 'Contestación a Procedimiento Administrativo Sancionador',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/contestacion-procedimiento-administrativo-sancionador.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Leyes Administrativas Generales","Art. 14 Constitucional"],
        description: 'Defensa inicial ante el inicio de un procedimiento sancionador de cualquier dependencia (PROFECO, COFEPRIS, STPS).',
        keywords: ["procedimiento sancionador","contestación acta inspección","visita verificación"],
    },
    {
        id: 'admin-solicitud-copias-v1',
        slug: 'solicitud-copias-certificadas',
        title: 'Solicitud de Copias Certificadas Administrativas',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/solicitud-copias-certificadas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 8 CPEUM","Art. 347 CFPC"],
        description: 'Formato simple para solicitar copias certificadas de expedientes o permisos a cualquier dependencia.',
        keywords: ["copias certificadas","solicitud expediente","reproducción oficial"],
    },
    {
        id: 'admin-desahogo-vista-v1',
        slug: 'desahogo-vista-administrativa',
        title: 'Desahogo de Vista (Administrativo)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/desahogo-vista-administrativa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["LFPA (Garantía de Audiencia)"],
        description: 'Documento para desahogar un emplazamiento o vista concedida por la autoridad antes de multar.',
        keywords: ["desahogo vista","garantía audiencia","LFPA"],
    },
    {
        id: 'admin-devolucion-indebido-v1',
        slug: 'solicitud-devolucion-pago-indebido-administrativo',
        title: 'Solicitud de Devolución de Pago de lo Indebido',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/solicitud-devolucion-pago-indebido-administrativo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Código Fiscal Local","Código Civil","Art. 8 CPEUM"],
        description: 'Reclamación de devolución por pagos dobles, cobros excesivos de derechos o multas anuladas ante la Tesorería.',
        keywords: ["pago indebido","devolución derechos","cobro excesivo tesorería"],
    },
    {
        id: 'admin-recurso-revision-sedatu-v1',
        slug: 'recurso-revision-sedatu-infonavit',
        title: 'Recurso de Revisión Administrativa (SEDATU / INFONAVIT)',
        specialty: 'administrativo',
        tier: 'v1',
        file: 'v1/administrativo/recurso-revision-sedatu-infonavit.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Vivienda","LFPA"],
        description: 'Modelo adaptado a litigios contra dependencias de territorio, vivienda o resoluciones de subsidios.',
        keywords: ["SEDATU","recurso revisión infonavit","subsidio vivienda administrativa"],
    },
];
