
export const templatesV1_migracion: Template[] = [
    {
        id: 'migracion-solicitud-visa-trabajo-v1',
        slug: 'solicitud-visa-trabajo-temporal-mexico',
        title: 'Solicitud de Visa de Trabajo Temporal en Mexico',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-visa-trabajo-temporal-mexico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Migracion Art. 52 Fr. III","Reglamento de la Ley de Migracion"],
        description: 'Solicitud ante el INM para obtener visa de trabajo temporal para extranjero que laborara en Mexico.',
        keywords: ["visa trabajo mexico extranjero","visa temporal laborar mexico","INM permiso trabajo"],
    },
    {
        id: 'migracion-cambio-condicion-estancia-v1',
        slug: 'solicitud-cambio-condicion-estancia-migratorio',
        title: 'Solicitud de Cambio de Condicion de Estancia Migratoria',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-cambio-condicion-estancia-migratorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 52-63 Ley de Migracion"],
        description: 'Solicitud ante el INM para cambiar la condicion de estancia del extranjero (ej. turista a residente temporal).',
        keywords: ["cambio condicion estancia mexico","turista a residente temporal","INM cambio visa"],
    },
    {
        id: 'migracion-renovacion-residente-temporal-v1',
        slug: 'solicitud-renovacion-tarjeta-residente-temporal',
        title: 'Solicitud de Renovacion de Tarjeta de Residente Temporal',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-renovacion-tarjeta-residente-temporal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 54 Ley de Migracion","Art. 108 Reglamento"],
        description: 'Tramite para renovar la vigencia de la tarjeta de residente temporal antes de su vencimiento.',
        keywords: ["renovar residente temporal mexico","tarjeta residente INM renovacion","prorroga estancia temporal"],
    },
    {
        id: 'migracion-solicitud-residente-permanente-v1',
        slug: 'solicitud-residente-permanente-mexico',
        title: 'Solicitud de Cambio a Residente Permanente en Mexico',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-residente-permanente-mexico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 55 Ley de Migracion","Arts. 113-121 Reglamento"],
        description: 'Solicitud para obtener la condicion de residente permanente tras cumplir los requisitos de tiempo o vinculo familiar.',
        keywords: ["residente permanente mexico","tarjeta residente permanente INM","residencia definitiva extranjero mexico"],
    },
    {
        id: 'migracion-recurso-revision-negativa-v1',
        slug: 'recurso-revision-negativa-tramite-migratorio',
        title: 'Recurso de Revision contra Negativa de Tramite Migratorio',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/recurso-revision-negativa-tramite-migratorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 152 Ley de Migracion","Arts. 83-94 Ley Federal de Procedimiento Administrativo"],
        description: 'Recurso administrativo contra la resolucion del INM que niega una solicitud migratoria.',
        keywords: ["recurso revision INM","impugnar negativa visa mexico","apelacion resolucion migratoria"],
    },
    {
        id: 'migracion-solicitud-refugio-v1',
        slug: 'solicitud-reconocimiento-condicion-refugiado',
        title: 'Solicitud de Reconocimiento de la Condicion de Refugiado',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-reconocimiento-condicion-refugiado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley sobre Refugiados, Proteccion Complementaria y Asilo Politico","Convenio 1951 ONU"],
        description: 'Solicitud ante la COMAR para obtener el reconocimiento de la condicion de refugiado en Mexico.',
        keywords: ["refugiado mexico comar","asilo mexico solicitud","proteccion internacional extranjero"],
    },
    {
        id: 'migracion-acta-abandono-v1',
        slug: 'acta-abandono-tramite-migratorio',
        title: 'Acta de Abandono Voluntario del Territorio Nacional',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/acta-abandono-tramite-migratorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 118 Ley de Migracion"],
        description: 'Documento mediante el cual el extranjero en situacion migratoria irregular opta por abandonar voluntariamente Mexico.',
        keywords: ["abandono voluntario mexico extranjero","salida voluntaria migratorio","extranjero irregular salida"],
    },
    {
        id: 'migracion-tutela-menor-extranjero-v1',
        slug: 'solicitud-tutela-menor-extranjero-no-acompanado',
        title: 'Solicitud de Tutela para Menor Extranjero No Acompanado',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-tutela-menor-extranjero-no-acompanado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 112 Ley de Migracion","Art. 4 CPEUM"],
        description: 'Solicitud para que el DIF asuma la tutela provisional de un menor extranjero no acompanado detectado en Mexico.',
        keywords: ["menor extranjero no acompanado","tutela dif menor migrante","nino migrante proteccion mexico"],
    },
    {
        id: 'migracion-amparo-expulsion-v1',
        slug: 'amparo-contra-orden-expulsion-extranjero',
        title: 'Amparo contra Orden de Expulsion de Extranjero',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/amparo-contra-orden-expulsion-extranjero.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 107 CPEUM","Ley de Amparo","Art. 118 Ley de Migracion"],
        description: 'Juicio de amparo para suspender una orden de deportacion o expulsion que vulnera derechos del extranjero.',
        keywords: ["amparo deportacion mexico","suspender expulsion extranjero","amparo migratorio deportacion"],
    },
    {
        id: 'migracion-carta-invitacion-v1',
        slug: 'carta-invitacion-extranjero-visitante',
        title: 'Carta de Invitacion para Extranjero Visitante',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/carta-invitacion-extranjero-visitante.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 40 Ley de Migracion"],
        description: 'Documento que una persona moral o fisica en Mexico extiende para respaldar la visita de un extranjero.',
        keywords: ["carta invitacion extranjero mexico","invitacion visa visitante","respaldo visitante extranjero"],
    },
    {
        id: 'migracion-proteccion-complementaria-v1',
        slug: 'solicitud-proteccion-complementaria-migracion',
        title: 'Solicitud de Proteccion Complementaria Migratoria',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-proteccion-complementaria-migracion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 2 Ley sobre Refugiados y Proteccion Complementaria"],
        description: 'Solicitud de proteccion para quien no califica como refugiado pero enfrentaria dano grave si regresa a su pais.',
        keywords: ["proteccion complementaria comar","asilo complementario mexico","dano grave deportacion extranjero"],
    },
    {
        id: 'migracion-asilo-politico-v1',
        slug: 'solicitud-asilo-politico-mexico',
        title: 'Solicitud de Asilo Politico en Mexico',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-asilo-politico-mexico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 60-65 Ley sobre Refugiados","Convencion de Caracas 1954"],
        description: 'Solicitud de asilo politico para perseguido por actividad politica en su pais de origen.',
        keywords: ["asilo politico mexico","solicitud asilo opositor","proteccion activista politico mexico"],
    },
    {
        id: 'migracion-queja-derechos-v1',
        slug: 'queja-violacion-derechos-migrante',
        title: 'Queja por Violacion de Derechos de Migrante ante CNDH',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/queja-violacion-derechos-migrante.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 11 CPEUM","Art. 66 Ley de Migracion"],
        description: 'Queja formal ante la CNDH por actos de autoridad que vulneran los derechos humanos de un migrante.',
        keywords: ["derechos migrante mexico","queja cndh migrante","derechos humanos extranjero mexico"],
    },
    {
        id: 'migracion-naturalizacion-v1',
        slug: 'solicitud-carta-naturalizacion-mexico',
        title: 'Solicitud de Carta de Naturalizacion Mexicana',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-carta-naturalizacion-mexico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 19-28 Ley de Nacionalidad"],
        description: 'Tramite ante la SRE para que un extranjero adquiera la nacionalidad mexicana por naturalizacion.',
        keywords: ["naturalizacion mexicana extranjero","carta naturalizacion mexico","nacionalidad mexicana solicitud"],
    },
    {
        id: 'migracion-reagrupacion-familiar-v1',
        slug: 'solicitud-reagrupacion-familiar-migratorio',
        title: 'Solicitud de Reagrupacion Familiar de Extranjero',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-reagrupacion-familiar-migratorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 52 Fr. IV Ley de Migracion","Art. 4 CPEUM"],
        description: 'Solicitud para que familiares de un residente legal en Mexico obtengan permiso de establecerse en el pais.',
        keywords: ["reagrupacion familiar extranjero mexico","visa familiar residente mexico","familia extranjero residencia"],
    },
    {
        id: 'migracion-denuncia-trata-v1',
        slug: 'denuncia-trata-personas-migrantes',
        title: 'Denuncia por Trata de Personas en Contexto Migratorio',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/denuncia-trata-personas-migrantes.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General para Prevenir la Trata de Personas","Arts. 207-210 CP Federal"],
        description: 'Denuncia penal por delito de trata de personas cometido contra migrantes en territorio nacional.',
        keywords: ["trata personas migrantes denuncia","trafico personas mexico","explotacion migrante denuncia"],
    },
    {
        id: 'migracion-recurso-inm-multa-v1',
        slug: 'recurso-contra-multa-inm-empleador',
        title: 'Recurso contra Multa del INM a Empleador',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/recurso-contra-multa-inm-empleador.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 153-160 Ley de Migracion"],
        description: 'Recurso de revision que interpone un empleador contra la multa impuesta por el INM por contratar trabajador sin permiso.',
        keywords: ["multa INM empleador extranjero","recurso multa migratorio","impugnar sancion INM empresa"],
    },
    {
        id: 'migracion-visa-estudiante-v1',
        slug: 'solicitud-visa-estudiante-extranjero',
        title: 'Solicitud de Visa de Estudiante Extranjero en Mexico',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-visa-estudiante-extranjero.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 40 Fr. II Ley de Migracion"],
        description: 'Solicitud de visa para extranjero que cursara estudios en institucion educativa reconocida en Mexico.',
        keywords: ["visa estudiante mexico extranjero","estudiar mexico visa","INM visa estudios superiores"],
    },
    {
        id: 'migracion-repatriacion-voluntaria-v1',
        slug: 'acuerdo-repatriacion-voluntaria-asistida',
        title: 'Acuerdo de Repatriacion Voluntaria Asistida',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/acuerdo-repatriacion-voluntaria-asistida.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 118 Ley de Migracion","Protocolo de Repatriacion SRE"],
        description: 'Documento de acuerdo voluntario para que un mexicano en el extranjero regrese al pais con asistencia consular.',
        keywords: ["repatriacion voluntaria mexicana","retorno asistido consulado","mexicano regreso pais apoyo"],
    },
    {
        id: 'migracion-certif-legal-estancia-v1',
        slug: 'solicitud-constancia-legal-estancia',
        title: 'Solicitud de Constancia de Estancia Legal',
        specialty: 'migracion',
        tier: 'v1',
        file: 'v1/migracion/solicitud-constancia-legal-estancia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 34 Ley de Migracion"],
        description: 'Solicitud de documento oficial que acredite la estancia legal del extranjero en Mexico para tramites ante terceros.',
        keywords: ["constancia estancia legal mexico","acreditar estancia INM","certificado migratorio legal mexico"],
    },
];
