
export const templatesV1_fiscal: Template[] = [
    {
        id: 'fiscal-declaracion-isr-persona-fisica-v1',
        slug: 'declaracion-anual-isr-persona-fisica',
        title: 'Declaración Anual ISR Persona Física',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/declaracion-anual-isr-persona-fisica.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 90-93 LISR","Art. 32-A CFF"],
        description: 'Escrito de presentación de declaración de ISR anual con determinación de impuesto o devolución.',
        keywords: ["declaración anual ISR","impuesto renta persona física","SAT declaración"],
    },
    {
        id: 'fiscal-demanda-nulidad-sat-v1',
        slug: 'demanda-nulidad-credito-fiscal-sat',
        title: 'Demanda de Nulidad de Crédito Fiscal',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/demanda-nulidad-credito-fiscal-sat.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 51, 52 Ley Federal de Procedimiento Contencioso Administrativo (LFPCA)"],
        description: 'Juicio ante el TFJA para anular crédito fiscal emitido por el SAT por vicios de forma o fondo.',
        keywords: ["nulidad crédito fiscal","TFJA SAT impugnar","juicio contencioso fiscal"],
    },
    {
        id: 'fiscal-recurso-revocacion-v1',
        slug: 'recurso-revocacion-sat-impuesto',
        title: 'Recurso de Revocación ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/recurso-revocacion-sat-impuesto.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 116-128 CFF"],
        description: 'Medio de defensa fiscal para impugnar resoluciones del SAT ante la propia autoridad fiscal.',
        keywords: ["recurso revocacion SAT","impugnar multa SAT","defensa fiscal administrativa"],
    },
    {
        id: 'fiscal-aclaracion-multa-v1',
        slug: 'aclaracion-multa-sat',
        title: 'Aclaración de Multa del SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/aclaracion-multa-sat.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 33-A CFF","Art. 70-A CFF"],
        description: 'Escrito para solicitar la condonación o reducción de multa fiscal cuando el contribuyente fue omiso por primera vez.',
        keywords: ["aclaracion multa SAT","condonacion multa","reduccion sancion fiscal"],
    },
    {
        id: 'fiscal-devolucion-iva-v1',
        slug: 'solicitud-devolucion-saldo-favor-iva',
        title: 'Solicitud de Devolución de Saldo a Favor de IVA',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-devolucion-saldo-favor-iva.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 22-22C CFF","Art. 6 LIVA"],
        description: 'Solicitar al SAT la devolución del saldo a favor generado en la declaración de IVA.',
        keywords: ["devolucion IVA","saldo favor IVA","reembolso SAT"],
    },
    {
        id: 'fiscal-acuerdo-conclusivo-v1',
        slug: 'solicitud-acuerdo-conclusivo-prodecon',
        title: 'Solicitud de Acuerdo Conclusivo ante la PRODECON',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-acuerdo-conclusivo-prodecon.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 69-C, 69-G CFF"],
        description: 'Alternativa de solución ante la PRODECON durante revisión del SAT para llegar a un acuerdo sin litigio.',
        keywords: ["acuerdo conclusivo PRODECON","mediacion SAT","terminar auditoria SAT"],
    },
    {
        id: 'fiscal-escrito-libre-sat-v1',
        slug: 'escrito-libre-sat-aclaracion',
        title: 'Escrito Libre ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/escrito-libre-sat-aclaracion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 18 CFF"],
        description: 'Comunicación general al SAT para aclarar, presentar información o comparecer ante requerimiento.',
        keywords: ["escrito libre SAT","respuesta requerimiento SAT","comunicacion fiscal"],
    },
    {
        id: 'fiscal-opinion-cumplimiento-v1',
        slug: 'solicitud-opinion-cumplimiento-fiscal',
        title: 'Solicitud de Opinión de Cumplimiento Fiscal',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-opinion-cumplimiento-fiscal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Regla 2.1.39 RMF 2025"],
        description: 'Gestión ante el SAT del certificado de opinión de cumplimiento de obligaciones fiscales (32D).',
        keywords: ["opinion cumplimiento SAT","constancia 32D","licitaciones opinion SAT"],
    },
    {
        id: 'fiscal-regularizacion-obligaciones-v1',
        slug: 'solicitud-condonacion-recargos-actualizaciones',
        title: 'Solicitud de Condonación de Recargos y Actualizaciones',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-condonacion-recargos-actualizaciones.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 74 CFF"],
        description: 'Petición de condonación de recargos y actualizaciones dentro de programas de regularización fiscal.',
        keywords: ["condonacion recargos SAT","regularizacion fiscal","quitas SAT"],
    },
    {
        id: 'fiscal-incidente-suspension-cobro-v1',
        slug: 'solicitud-suspension-ejecucion-credito-fiscal',
        title: 'Solicitud de Suspensión de Ejecución del Crédito Fiscal',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-suspension-ejecucion-credito-fiscal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 144-146 CFF"],
        description: 'Solicitud para suspender el procedimiento de ejecución fiscal mientras se resuelve el recurso o juicio.',
        keywords: ["suspension cobro SAT","paralizar credito fiscal","garantia interes fiscal"],
    },
    {
        id: 'fiscal-demanda-contencioso-tfja-v1',
        slug: 'demanda-juicio-contencioso-administrativo-fiscal',
        title: 'Demanda de Juicio en Línea ante el TFJA',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/demanda-juicio-contencioso-administrativo-fiscal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 13-16 LFPCA"],
        description: 'Presentación de demanda de nulidad por vía electrónica ante el Tribunal Federal de Justicia Administrativa.',
        keywords: ["juicio en linea TFJA","demanda TFJA electronica","nulidad via internet"],
    },
    {
        id: 'fiscal-amparo-fiscal-v1',
        slug: 'demanda-amparo-indirecto-fiscal',
        title: 'Demanda de Amparo Indirecto Fiscal',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/demanda-amparo-indirecto-fiscal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 103-107 CPEUM","Ley de Amparo"],
        description: 'Amparo contra leyes o actos de autoridades fiscales que violen garantías constitucionales del contribuyente.',
        keywords: ["amparo fiscal SAT","amparo contra impuesto","inconstitucionalidad ley fiscal"],
    },
    {
        id: 'fiscal-dictamen-fiscal-v1',
        slug: 'dictamen-fiscal-contador-publico',
        title: 'Informe de Dictamen Fiscal (CPC)',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/dictamen-fiscal-contador-publico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 52 CFF","Reglas RMF 2025"],
        description: 'Dictamen contable que presenta el Contador Público Certificado sobre los estados financieros del contribuyente.',
        keywords: ["dictamen fiscal CPC","auditor externo SAT","dictamen financiero"],
    },
    {
        id: 'fiscal-aviso-baja-v1',
        slug: 'aviso-baja-actividades-sat',
        title: 'Aviso de Baja de Actividades ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/aviso-baja-actividades-sat.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 25, 26 CFF","Ficha 77/CFF RMF 2025"],
        description: 'Trámite de baja de actividades cuando el contribuyente cesa operaciones definitivamente o cambia de régimen.',
        keywords: ["baja actividades SAT","cancelar RFC actividades","cierre empresa SAT"],
    },
    {
        id: 'fiscal-precios-transferencia-v1',
        slug: 'informe-precios-transferencia',
        title: 'Estudio de Precios de Transferencia',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/informe-precios-transferencia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 76 Fr. IX, 179-181 LISR","OCDE Guias PT"],
        description: 'Documento técnico de análisis de operaciones entre partes relacionadas y su comparabilidad con precios de mercado.',
        keywords: ["precios de transferencia","partes relacionadas SAT","estudio comparabilidad ISR"],
    },
    {
        id: 'fiscal-ampliacion-plazo-v1',
        slug: 'solicitud-ampliacion-plazo-presentacion',
        title: 'Solicitud de Ampliación de Plazo ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-ampliacion-plazo-presentacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 12 CFF","Regla 2.1.7 RMF 2025"],
        description: 'Escrito pidiendo al SAT más tiempo para atender un requerimiento o presentar documentación fiscal.',
        keywords: ["ampliacion plazo SAT","prorroga requerimiento","mas tiempo declaracion SAT"],
    },
    {
        id: 'fiscal-consulta-sat-v1',
        slug: 'consulta-fiscal-sat-criterio',
        title: 'Consulta Fiscal ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/consulta-fiscal-sat-criterio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 34-34-A CFF"],
        description: 'Petición del contribuyente para que el SAT emita un criterio vinculante sobre el tratamiento de una operación específica.',
        keywords: ["consulta SAT criterio","34 CFF consulta","tratamiento fiscal duda"],
    },
    {
        id: 'fiscal-isr-personas-morales-v1',
        slug: 'declaracion-anual-isr-personas-morales',
        title: 'Declaración Anual ISR Personas Morales',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/declaracion-anual-isr-personas-morales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 9-10 LISR"],
        description: 'Presentacion de la declaracion anual de ISR de una SA o SRL con calculo de PTU y saldo a favor.',
        keywords: ["declaracion anual ISR moral","DIOT personas morales","ISR empresa declaracion"],
    },
    {
        id: 'fiscal-acuerdo-pago-credito-v1',
        slug: 'solicitud-pago-parcialidades-credito-fiscal',
        title: 'Solicitud de Pago en Parcialidades de Crédito Fiscal',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/solicitud-pago-parcialidades-credito-fiscal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 66-66-A CFF"],
        description: 'Petición para cubrir un crédito fiscal determinado en cuotas mensuales cuando no hay liquidez inmediata.',
        keywords: ["pago parcialidades SAT","deuda SAT en cuotas","diferir adeudo fiscal"],
    },
    {
        id: 'fiscal-recurso-revocacion-sat-v1',
        slug: 'recurso-revocacion-sat',
        title: 'Recurso de Revocacion ante el SAT',
        specialty: 'fiscal',
        tier: 'v1',
        file: 'v1/fiscal/recurso-revocacion-sat.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 116-128 CFF"],
        description: 'Medio de defensa fiscal para impugnar resoluciones del SAT ante la propia autoridad.',
        keywords: ["recurso revocacion SAT","impugnar multa SAT","defensa fiscal administrativa"],
    },
];
