
export const templatesV1_amparo: Template[] = [
    {
        id: 'amparo-indirecto-penal-v1',
        slug: 'demanda-amparo-indirecto-orden-aprehension',
        title: 'Demanda Amparo Indirecto contra Orden de Aprehensión',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-indirecto-orden-aprehension.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 107 Constitucional","Ley de Amparo Art. 107 Fracc V"],
        description: 'Amparo indirecto para proteger la libertad personal ante una orden de captura inminente (Buscadores).',
        keywords: ["amparo orden aprehensión","amparo buscador penal","suspensión libertad","amparo indirecto"],
    },
    {
        id: 'amparo-directo-civil-v1',
        slug: 'demanda-amparo-directo-materia-civil',
        title: 'Demanda de Amparo Directo en Materia Civil',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-directo-materia-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 170 Ley de Amparo"],
        description: 'Amparo contra sentencias definitivas dictadas por Salas Civiles o Familiares de segunda instancia.',
        keywords: ["amparo directo civil","amparo sentencia definitiva","casación civil amparo"],
    },
    {
        id: 'amparo-indirecto-administrativa-v1',
        slug: 'demanda-amparo-indirecto-clausura',
        title: 'Amparo Indirecto por Clausura de Negocio',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-indirecto-clausura.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 107 y 114 Ley de Amparo"],
        description: 'Amparo indirecto solicitando la suspensión contra actos de verificación y clausuras administrativas fuera de orden.',
        keywords: ["amparo clausura local","amparo administrativo negocio","suspensión sellos clausura"],
    },
    {
        id: 'amparo-directo-laboral-v1',
        slug: 'demanda-amparo-directo-laudo-laboral',
        title: 'Demanda de Amparo Directo Laboral (Contra Laudo)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-directo-laudo-laboral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 170 Ley de Amparo","Ley Federal del Trabajo"],
        description: 'Amparo directo interpuesto por el trabajador o el patrón en contra del laudo definitivo dictado por la Junta o el Tribunal Laboral.',
        keywords: ["amparo laudo","amparo directo laboral","tribunal colegiado laboral","impugnar despido"],
    },
    {
        id: 'amparo-directo-agrario-v1',
        slug: 'demanda-amparo-directo-materia-agraria',
        title: 'Demanda de Amparo Directo Agrario',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-directo-materia-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 170 Ley de Amparo","Ley Agraria"],
        description: 'Amparo promovido por ejidatarios o comuneros contra resoluciones (sentencias) de los Tribunales Unitarios Agrarios.',
        keywords: ["amparo agrario","TUA amparo directo","amparo sentencia tribunal agrario"],
    },
    {
        id: 'amparo-recurso-revision-v1',
        slug: 'recurso-revision-contra-sentencia-juez-distrito',
        title: 'Recurso de Revisión en Amparo (Contra Sentencia Constitucional)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/recurso-revision-contra-sentencia-juez-distrito.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 81-86 Ley de Amparo"],
        description: 'Recurso interpuesto ante un Tribunal Colegiado para impugnar la sentencia dictada por un Juez de Distrito en un amparo indirecto.',
        keywords: ["recurso de revisión amparo","agravios revisión constitucional","impugnar negativa de amparo"],
    },
    {
        id: 'amparo-recurso-queja-v1',
        slug: 'recurso-queja-desechamiento-demanda-amparo',
        title: 'Recurso de Queja (Contra Desechamiento de Demanda)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/recurso-queja-desechamiento-demanda-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 97 Fracción I Ley de Amparo"],
        description: 'Medio de impugnación contra el auto inicial del Juez de Distrito que desecha de plano la demanda de amparo.',
        keywords: ["recurso de queja","desechamiento amparo","admisión de demanda"],
    },
    {
        id: 'amparo-solicitud-suspension-v1',
        slug: 'solicitud-apertura-incidente-suspension',
        title: 'Solicitud de Suspensión (Apertura de Incidente)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/solicitud-apertura-incidente-suspension.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 125, 128 Ley de Amparo"],
        description: 'Escrito solicitando la suspensión del acto reclamado si no se pidió expresamente en la demanda inicial.',
        keywords: ["solicitud suspensión amparo","incidente de suspensión","paralización acto reclamado"],
    },
    {
        id: 'amparo-incidente-nulidad-v1',
        slug: 'incidente-nulidad-notificaciones-amparo',
        title: 'Incidente de Nulidad de Notificaciones en Amparo',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/incidente-nulidad-notificaciones-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 68 Ley de Amparo"],
        description: 'Recurso incidental para anular una notificación personal viciada o la publicación indebida en la lista del Juzgado Federal.',
        keywords: ["nulidad notificaciones amparo","incidente nulidad ley de amparo","emplazamiento amparo"],
    },
    {
        id: 'amparo-ampliacion-demanda-v1',
        slug: 'escrito-ampliacion-demanda-amparo',
        title: 'Escrito de Ampliación de Demanda de Amparo',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/escrito-ampliacion-demanda-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 111 Ley de Amparo"],
        description: 'Ampliación cuando del informe justificado resulten nuevos actos, nuevas autoridades responsables o nuevos argumentos.',
        keywords: ["ampliación demanda amparo","amparo nuevos actos","informe justificado ampliación"],
    },
    {
        id: 'amparo-agravios-revision-v1',
        slug: 'agravios-recurso-revision-amparo',
        title: 'Escrito de Expresión de Agravios en Recurso Revisión',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/agravios-recurso-revision-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 88 Ley de Amparo"],
        description: 'Documento anexo o principal que desgrana los errores doctrinales y legales cometidos por un Juez de Distrito al fallar.',
        keywords: ["agravios amparo en revisión","formulación de agravios colegiado"],
    },
    {
        id: 'amparo-alegatos-informe-v1',
        slug: 'contestacion-informe-justificado-alegatos-amparo',
        title: 'Alegatos de Contestación al Informe Justificado',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/contestacion-informe-justificado-alegatos-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 124 Ley de Amparo"],
        description: 'Alegatos presentados por quejoso o tercero interesado antes o durante la Audiencia Constitucional del Amparo Indirecto.',
        keywords: ["alegatos audiencia constitucional","informe justificado manifestaciones amparo"],
    },
    {
        id: 'amparo-pruebas-suspension-v1',
        slug: 'ofrecimiento-pruebas-incidente-suspension',
        title: 'Ofrecimiento de Pruebas en Incidente de Suspensión',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/ofrecimiento-pruebas-incidente-suspension.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 143 Ley de Amparo"],
        description: 'Format para ofrecer la prueba documental, de inspección o confesional específica dentro del cuaderno incidental.',
        keywords: ["pruebas incidente de suspensión","documental cuaderno incidental","amparo pruebas suspensión"],
    },
    {
        id: 'amparo-pruebas-principal-v1',
        slug: 'ofrecimiento-pruebas-juicio-principal-amparo',
        title: 'Ofrecimiento de Pruebas en Amparo Principal',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/ofrecimiento-pruebas-juicio-principal-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 119 Ley de Amparo"],
        description: 'Ofrecimiento de periciales, testimoniales y documentales en el juicio principal (con los tiempos de preclusión requeridos).',
        keywords: ["pruebas juicio amparo","ofrecimiento pericial federal","audiencia constitucional pruebas"],
    },
    {
        id: 'amparo-causar-ejecutoria-v1',
        slug: 'promocion-causar-ejecutoria-sentencia-amparo',
        title: 'Solicitud para Declarar que Causó Ejecutoria el Amparo',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/promocion-causar-ejecutoria-sentencia-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 356 CFPC aplicable supletoriamente"],
        description: 'Cuando ha transcurrido el tiempo legal para interponer recurso de revisión y la sentencia dictada en Amparo ha quedado firme.',
        keywords: ["sentencia ejecutoriada amparo","sentencia firme federal","auto causa estado amparo"],
    },
    {
        id: 'amparo-inejecucion-sentencia-v1',
        slug: 'incidente-inejecucion-sentencia-amparo',
        title: 'Incidente de Inejecución de Sentencia',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/incidente-inejecucion-sentencia-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 192 y subsiguientes de la Ley de Amparo"],
        description: 'Amparo otorgado que la autoridad responsable se niega a cumplir, pidiendo apercibimiento y posible destitución.',
        keywords: ["inejecución amparo","rebeldía autoridad amparo","desacato cumplimiento amparo","SCJN destitución"],
    },
    {
        id: 'amparo-recurso-inconformidad-v1',
        slug: 'recurso-inconformidad-cumplimiento-amparo',
        title: 'Recurso de Inconformidad (Cumplimiento Defectuoso)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/recurso-inconformidad-cumplimiento-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 201 Fracción I Ley de Amparo"],
        description: 'Impugnación cuando el Juez de Distrito tiene por cumplida la sentencia de amparo pero el quejoso considera que el cumplimiento fue engañoso, defectuoso o excesivo.',
        keywords: ["inconformidad amparo","cumplimiento defectuoso amparo","sentencia de amparo mal cumplida"],
    },
    {
        id: 'amparo-indirecto-leyes-v1',
        slug: 'demanda-amparo-indirecto-leyes-autoaplicativas',
        title: 'Demanda de Amparo Indirecto contra Leyes',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/demanda-amparo-indirecto-leyes-autoaplicativas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 107 Fracción I de Ley de Amparo"],
        description: 'Amparo promovido dentro de los 30 días siguientes a la entrada en vigor de una norma general (ley, decreto, reglamento) que causa perjuicio con su sola entrada.',
        keywords: ["amparo contra leyes","amparo autoaplicativa","amparo ley fiscal nuevo impuesto"],
    },
    {
        id: 'amparo-devolucion-garantia-v1',
        slug: 'escrito-devolucion-billete-deposito-fianza-amparo',
        title: 'Solicitud de Devolución de Garantía (Fianza/Billete Amparo)',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/escrito-devolucion-billete-deposito-fianza-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 156 Ley de Amparo"],
        description: 'Una vez terminado el amparo, solicitar al Juzgado que devuelva el dinero depositado en garantía por la suspensión otorgada.',
        keywords: ["devolución billete depósito Bansefi","fianza amparo devolución","devolver garantía económica"],
    },
    {
        id: 'amparo-recurso-revocacion-v1',
        slug: 'recurso-revocacion-amparo',
        title: 'Recurso de Revocación en Amparo',
        specialty: 'amparo',
        tier: 'v1',
        file: 'v1/amparo/recurso-revocacion-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 266 Ley de Amparo"],
        description: 'Medio de impugnación contra acuerdos de trámite que dicte el presidente de la Suprema Corte o los Colegiados.',
        keywords: ["revocación amparo","impugnar trámite colegiado"],
    },
];
