
export const templatesV1_civil: Template[] = [
    {
        id: 'civil-demanda-deuda-v1',
        slug: 'demanda-pago-deuda-civil',
        title: 'Demanda Civil por Pago de Deuda',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-pago-deuda-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1859-1950 CCDF"],
        description: 'Demanda por deuda líquida y exigible entre particulares.',
        keywords: ["cobro deuda civil","pagaré vencido","prestamo civil"],
    },
    {
        id: 'civil-contestacion-demanda-v1',
        slug: 'contestacion-demanda-civil',
        title: 'Contestación de Demanda Civil',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/contestacion-demanda-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["CPCCDF Arts. 260-280"],
        description: 'Escrito de contestación oponiendo excepciones dilatorias y perentorias.',
        keywords: ["contestación civil","espera y quitas","pago parcial"],
    },
    {
        id: 'civil-reconvencion-v1',
        slug: 'demanda-reconvencional-civil',
        title: 'Demanda Reconvencional Civil',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-reconvencional-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 271 CPCDF"],
        description: 'Contrademanda interpuesta por el demandado al contestar la demanda principal.',
        keywords: ["reconvención civil","contrademanda"],
    },
    {
        id: 'civil-daño-moral-v1',
        slug: 'demanda-dano-moral',
        title: 'Demanda por Daño Moral',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-dano-moral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1916 CCDF"],
        description: 'Reclamo civil por afectación de honor, imagen o sentimientos por acto ilícito.',
        keywords: ["daño moral","difamación civil","indemnización moral"],
    },
    {
        id: 'civil-prescripcion-adquisitiva-v1',
        slug: 'demanda-prescripcion-adquisitiva-civil',
        title: 'Demanda de Prescripción Adquisitiva',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-prescripcion-adquisitiva-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1135-1156 CCDF"],
        description: 'Usucapión civil para regularizar inmueble poseído más de 5 años de buena fe.',
        keywords: ["usucapión","prescripción positiva","regularizar inmueble"],
    },
    {
        id: 'civil-nulidad-acto-v1',
        slug: 'demanda-nulidad-acto-juridico',
        title: 'Demanda de Nulidad de Acto Jurídico',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-nulidad-acto-juridico.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1794-1859 CCDF"],
        description: 'Nulidad absoluta o relativa de contrato por vicios del consentimiento o ilicitud.',
        keywords: ["nulidad contrato","dolo error","rescisión civil"],
    },
    {
        id: 'civil-cumplimiento-contrato-v1',
        slug: 'demanda-cumplimiento-contrato-civil',
        title: 'Demanda de Cumplimiento de Contrato',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-cumplimiento-contrato-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1949 CCDF"],
        description: 'Ejecución forzosa de la obligación pactada cuando el deudor incumple.',
        keywords: ["cumplimiento forzoso","ejecución contrato civil"],
    },
    {
        id: 'civil-rescision-contrato-v1',
        slug: 'demanda-rescision-contrato-civil',
        title: 'Demanda de Rescisión de Contrato Civil',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-rescision-contrato-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1949 CCDF"],
        description: 'Terminar el contrato por incumplimiento más reclamación de daños y perjuicios.',
        keywords: ["rescisión contrato","resolución civil","daños incumplimiento"],
    },
    {
        id: 'civil-sucesion-testamentaria-v1',
        slug: 'apertura-juicio-sucesorio-testamentario',
        title: 'Apertura de Sucesión Testamentaria',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/apertura-juicio-sucesorio-testamentario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1288-1350 CCDF"],
        description: 'Solicitud de apertura de juicio sucesorio con testamento público.',
        keywords: ["sucesión testamentaria","herencia con testamento","albacea"],
    },
    {
        id: 'civil-sucesion-intestamentaria-v1',
        slug: 'apertura-sucesion-intestamentaria-civil',
        title: 'Solicitud de Sucesión Intestamentaria',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/apertura-sucesion-intestamentaria-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1599-1636 CCDF"],
        description: 'Apertura de sucesión cuando el fallecido no dejó testamento.',
        keywords: ["intestamentario","herencia sin testamento","intestado"],
    },
    {
        id: 'civil-desocupacion-v1',
        slug: 'demanda-desocupacion-inmueble',
        title: 'Demanda de Desocupación de Inmueble',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-desocupacion-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2398-2496 CCDF"],
        description: 'Acción para que el inquilino desocupe al vencer el contrato o incumplir pago.',
        keywords: ["desocupación rentado","desahucio arrendamiento","terminación arrendamiento"],
    },
    {
        id: 'civil-accion-pauliana-v1',
        slug: 'demanda-accion-pauliana',
        title: 'Acción Pauliana (Fraude de Acreedores)',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-accion-pauliana.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2163-2179 CCDF"],
        description: 'Rescisión de actos fraudulentos del deudor realizados en perjuicio del acreedor.',
        keywords: ["acción pauliana","fraude acreedores","insolvencia civil"],
    },
    {
        id: 'civil-interdicto-v1',
        slug: 'interdicto-amparo-posesion',
        title: 'Interdicto de Amparo a la Posesión',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/interdicto-amparo-posesion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 16-18 CPCDF"],
        description: 'Acción inmediata para cesar actos de perturbación a la posesión de un inmueble.',
        keywords: ["interdicto","perturbación posesión","despojo civil"],
    },
    {
        id: 'civil-rendicion-cuentas-v1',
        slug: 'demanda-rendicion-cuentas',
        title: 'Demanda de Rendición de Cuentas',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-rendicion-cuentas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2569-2583 CCDF"],
        description: 'Obliga a mandatarios o administradores a presentar cuentas detalladas de su gestión.',
        keywords: ["rendición cuentas","mandato civil","gestión patrimonial"],
    },
    {
        id: 'civil-ofrecimiento-pago-v1',
        slug: 'ofrecimiento-pago-consignacion',
        title: 'Ofrecimiento de Pago por Consignación',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/ofrecimiento-pago-consignacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2097-2111 CCDF"],
        description: 'Cuando el acreedor se niega a recibir, el deudor consigna judicialmente.',
        keywords: ["pago por consignación","acreedor renuente"],
    },
    {
        id: 'civil-tutela-v1',
        slug: 'solicitud-tutela-legitima',
        title: 'Solicitud de Tutela Legítima',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/solicitud-tutela-legitima.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 462-543 CCDF"],
        description: 'Nombramiento de tutor para mayor de edad declarado en estado de interdicción.',
        keywords: ["tutela legítima","interdicción civil","curador"],
    },
    {
        id: 'civil-jactancia-v1',
        slug: 'demanda-jactancia',
        title: 'Demanda de Jactancia',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-jactancia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 4-10 CPCDF"],
        description: 'Obliga a quien alardea de derechos a demandar formalmente o a callar definitivamente.',
        keywords: ["jactancia civil","acción jactancia","derechos presuntos"],
    },
    {
        id: 'civil-incidente-liquidacion-v1',
        slug: 'incidente-liquidacion-condena',
        title: 'Incidente de Liquidación de Condena',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/incidente-liquidacion-condena.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 514 CPCDF"],
        description: 'Cuantificación exacta de daños e intereses tras obtener sentencia favorable.',
        keywords: ["liquidación condena","cuantificar daños civiles","incidente ejecución"],
    },
    {
        id: 'civil-divorcio-mutuo-v1',
        slug: 'divorcio-mutuo-consentimiento',
        title: 'Solicitud de Divorcio por Mutuo Consentimiento',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/divorcio-mutuo-consentimiento.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 266 CCDF"],
        description: 'Divorcio amistoso sin hijos menores cuando ambos cónyuges están de acuerdo.',
        keywords: ["divorcio mutuo acuerdo","divorcio amistoso"],
    },
    {
        id: 'civil-daños-materiales-v1',
        slug: 'demanda-danos-perjuicios-materiales',
        title: 'Demanda de Daños y Perjuicios Materiales',
        specialty: 'civil',
        tier: 'v1',
        file: 'v1/civil/demanda-danos-perjuicios-materiales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2104-2111 CCDF"],
        description: 'Reclamación por daño material ocasionado ya sea por accidente, negligencia o incumplimiento.',
        keywords: ["daños materiales","perjuicios civiles","accidente negligencia"],
    },
];
