
export const templatesV1_intelectual: Template[] = [
    {
        id: 'pi-registro-marca-v1',
        slug: 'solicitud-registro-marca-impi',
        title: 'Solicitud de Registro de Marca ante el IMPI',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-registro-marca-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 87-111 Ley de Propiedad Industrial"],
        description: 'Tramite para registrar una marca comercial, de servicios, colectiva o de certificacion.',
        keywords: ["registro marca IMPI","marca comercial registro","proteger marca Mexico"],
    },
    {
        id: 'pi-demanda-infraccion-marca-v1',
        slug: 'demanda-infraccion-marca-registrada',
        title: 'Demanda por Infracción de Marca Registrada',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/demanda-infraccion-marca-registrada.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 213-218 Ley de Propiedad Industrial"],
        description: 'Accion ante el IMPI para declarar la infraccion por uso no autorizado de marca registrada.',
        keywords: ["infraccion marca","plagio marca comercial","usurpar marca IMPI"],
    },
    {
        id: 'pi-registro-patente-v1',
        slug: 'solicitud-patente-invencion-impi',
        title: 'Solicitud de Patente de Invención',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-patente-invencion-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 15-52 Ley de Propiedad Industrial"],
        description: 'Tramite para proteger una invencion nueva, con nivel inventivo y aplicacion industrial.',
        keywords: ["registro patente IMPI","patente invencion Mexico","proteger invencion IMPI"],
    },
    {
        id: 'pi-licencia-marca-v1',
        slug: 'contrato-licencia-uso-marca',
        title: 'Contrato de Licencia de Uso de Marca',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/contrato-licencia-uso-marca.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 136-140 Ley de Propiedad Industrial"],
        description: 'Acuerdo por el cual el titular de una marca autoriza a terceros su uso bajo terminos y condiciones.',
        keywords: ["licencia marca contrato","autorizar uso marca","royalties marca mexico"],
    },
    {
        id: 'pi-registro-derecho-autor-v1',
        slug: 'registro-obra-indautor',
        title: 'Registro de Obra ante el INDAUTOR',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/registro-obra-indautor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 18-29 Ley Federal del Derecho de Autor"],
        description: 'Tramite para registrar una obra literaria, artistica, musical o de software ante el INDAUTOR.',
        keywords: ["registro derecho autor","INDAUTOR registrar obra","proteger obra creativa"],
    },
    {
        id: 'pi-demanda-violacion-derechos-autor-v1',
        slug: 'demanda-violacion-derechos-autor',
        title: 'Demanda por Violación de Derechos de Autor',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/demanda-violacion-derechos-autor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 213-234 Ley Federal del Derecho de Autor"],
        description: 'Accion civil o penal contra quien reproduzca, distribuya o modifique una obra sin autorizacion del titular.',
        keywords: ["pirateria derechos autor","plagio obra literaria","infraccion copyright Mexico"],
    },
    {
        id: 'pi-nombre-comercial-v1',
        slug: 'solicitud-nombre-comercial-impi',
        title: 'Solicitud de Nombre Comercial',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-nombre-comercial-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 105-110 Ley de Propiedad Industrial"],
        description: 'Tramite ante el IMPI para proteger el nombre de un negocio o establecimiento como nombre comercial.',
        keywords: ["nombre comercial IMPI","proteger nombre empresa","registro comercio IMPI"],
    },
    {
        id: 'pi-contrato-transferencia-tecnologia-v1',
        slug: 'contrato-transferencia-tecnologia',
        title: 'Contrato de Transferencia de Tecnología',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/contrato-transferencia-tecnologia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 145-164 Ley de Propiedad Industrial","CFF Art. 15-B"],
        description: 'Acuerdo por el que el titular de tecnologia o know-how la transmite o licencia a un adquirente.',
        keywords: ["transferencia tecnologia contrato","licencia know-how","tecnologia industrial mexico"],
    },
    {
        id: 'pi-modelo-utilidad-v1',
        slug: 'solicitud-modelo-utilidad-impi',
        title: 'Solicitud de Modelo de Utilidad',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-modelo-utilidad-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 28-32 Ley de Propiedad Industrial"],
        description: 'Proteccion de mejoras a objetos, utensilios o dispositivos que los hacen mas utiles sin ser una invencion mayor.',
        keywords: ["modelo de utilidad IMPI","mejora industrial proteger","utilidad objeto mejorado"],
    },
    {
        id: 'pi-diseno-industrial-v1',
        slug: 'solicitud-registro-diseno-industrial',
        title: 'Solicitud de Registro de Diseño Industrial',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-registro-diseno-industrial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 33-47 Ley de Propiedad Industrial"],
        description: 'Proteccion del aspecto ornamental de un producto que lo hace visualmente distinto.',
        keywords: ["diseno industrial IMPI","registro apariencia producto","estética industrial proteger"],
    },
    {
        id: 'pi-cedula-agente-pi-v1',
        slug: 'carta-poder-agente-propiedad-industrial',
        title: 'Carta Poder para Agente de Propiedad Industrial',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/carta-poder-agente-propiedad-industrial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 6 Ley de Propiedad Industrial"],
        description: 'Poder notarial para que un agente de PI actue en representacion del titular ante el IMPI.',
        keywords: ["poder agente IMPI","carta poder propiedad industrial","representante IMPI"],
    },
    {
        id: 'pi-declaracion-nulidad-marca-v1',
        slug: 'demanda-nulidad-registro-marca',
        title: 'Demanda de Nulidad de Registro de Marca',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/demanda-nulidad-registro-marca.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 151-157 Ley de Propiedad Industrial"],
        description: 'Accion ante el IMPI para cancelar un registro de marca obtenido de mala fe o que viola derechos previos.',
        keywords: ["nulidad marca IMPI","cancelar registro marca","mala fe registro marca"],
    },
    {
        id: 'pi-registro-secreto-industrial-v1',
        slug: 'acuerdo-proteccion-secreto-industrial',
        title: 'Acuerdo de Protección de Secreto Industrial',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/acuerdo-proteccion-secreto-industrial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 82-91 Ley de Propiedad Industrial"],
        description: 'Contrato de confidencialidad para proteger el secreto industrial de una empresa frente a empleados y socios.',
        keywords: ["secreto industrial contrato","NDA empresa","confidencialidad informacion tecnica"],
    },
    {
        id: 'pi-contrato-cesion-derechos-v1',
        slug: 'contrato-cesion-derechos-autor',
        title: 'Contrato de Cesión de Derechos de Autor',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/contrato-cesion-derechos-autor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 26-30 Ley Federal del Derecho de Autor"],
        description: 'Acuerdo mediante el cual el autor cede total o parcialmente sus derechos patrimoniales a otro titular.',
        keywords: ["cesion derechos autor","transferir copyright","editorial contrato autor"],
    },
    {
        id: 'pi-impugnacion-resolucion-impi-v1',
        slug: 'recurso-revision-resolucion-impi',
        title: 'Recurso de Revisión contra Resolución del IMPI',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/recurso-revision-resolucion-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 83 LFPA","Arts. 186-191 Ley de Propiedad Industrial"],
        description: 'Recurso para impugnar ante el Director General del IMPI una resolucion desfavorable en tramite de marca o patente.',
        keywords: ["recurso revision IMPI","impugnar negativa marca","apelar IMPI"],
    },
    {
        id: 'pi-contrato-edicion-v1',
        slug: 'contrato-edicion-obra',
        title: 'Contrato de Edición de Obra',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/contrato-edicion-obra.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 41-52 Ley Federal del Derecho de Autor"],
        description: 'Acuerdo especifico para la publicacion de una obra, con tirada, precio, plazo y distribucion.',
        keywords: ["contrato edicion obra","publicar libro editorial","tirada editorial contrato"],
    },
    {
        id: 'pi-proteccion-software-v1',
        slug: 'registro-software-indautor',
        title: 'Registro de Software ante el INDAUTOR',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/registro-software-indautor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 101-114 Ley Federal del Derecho de Autor"],
        description: 'Proteccion del codigo fuente de un software como obra de autor ante el INDAUTOR.',
        keywords: ["registro software INDAUTOR","copyright programa informatico","proteger codigo fuente"],
    },
    {
        id: 'pi-licencia-software-v1',
        slug: 'contrato-licencia-uso-software',
        title: 'Contrato de Licencia de Uso de Software',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/contrato-licencia-uso-software.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 101-114 LFDA","Arts. 1792 CCDF"],
        description: 'Acuerdo que otorga al usuario el derecho de uso del software bajo terminos y condiciones especificas.',
        keywords: ["licencia software contrato","EULA mexico","uso programa computadora contrato"],
    },
    {
        id: 'pi-acuerdo-confidencialidad-v1',
        slug: 'acuerdo-confidencialidad-nda',
        title: 'Acuerdo de Confidencialidad (NDA)',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/acuerdo-confidencialidad-nda.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1792-1797 CCDF","Art. 82 LPI"],
        description: 'Contrato de no divulgacion para proteger informacion confidencial antes de negociaciones o relaciones comerciales.',
        keywords: ["NDA acuerdo confidencialidad","no divulgacion contrato","proteger informacion empresa"],
    },
    {
        id: 'pi-indicacion-geografica-v1',
        slug: 'solicitud-indicacion-geografica-impi',
        title: 'Solicitud de Indicación Geográfica',
        specialty: 'intelectual',
        tier: 'v1',
        file: 'v1/intelectual/solicitud-indicacion-geografica-impi.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 166-180 Ley de Propiedad Industrial"],
        description: 'Proteccion del nombre geografico que identifica un producto cuyas cualidades se deben al lugar de origen.',
        keywords: ["indicacion geografica IMPI","denominacion origen Mexico","registro indicacion geografica"],
    },
];
