
export const templatesV1_agrario: Template[] = [
    {
        id: 'agrario-demanda-inicial-v1',
        slug: 'demanda-agraria-restitucion-tierras',
        title: 'Demanda Agraria Inicial (Restitución de Tierras)',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/demanda-agraria-restitucion-tierras.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2, 9, 27 CPEUM","Arts. 49, 163 Ley Agraria"],
        description: 'Demanda inicial ante Tribunal Unitario Agrario para restitución de superficie parcelaria o comunal.',
        keywords: ["demanda agraria","restitución tierras","tribunal unitario agrario","ejido"],
    },
    {
        id: 'agrario-nulidad-asamblea-v1',
        slug: 'demanda-nulidad-actas-asamblea-ejidal',
        title: 'Demanda de Nulidad de Actas de Asamblea Ejidal',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/demanda-nulidad-actas-asamblea-ejidal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 22-31 Ley Agraria"],
        description: 'Juicio para anular acuerdos tomados en asamblea por falta de quórum o formalidades.',
        keywords: ["nulidad asamblea","comisariado ejidal","ley agraria","asamblea ejidatarios"],
    },
    {
        id: 'agrario-sucesion-intestamentaria-v1',
        slug: 'demanda-sucesion-agraria',
        title: 'Juicio Sucesorio Agrario Intestamentario',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/demanda-sucesion-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 17, 18, 19 Ley Agraria"],
        description: 'Trámite TUA para transmisión de derechos agrarios a sucesores legales por ausencia de lista de sucesión.',
        keywords: ["sucesión agraria","intestamentario ejidal","derechos parcelarios","viuda ejidatario"],
    },
    {
        id: 'agrario-repudio-derechos-v1',
        slug: 'escrito-repudio-derechos-agrarios',
        title: 'Escrito de Repudio de Sucesión Agraria',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/escrito-repudio-derechos-agrarios.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 18 Ley Agraria"],
        description: 'Renuncia a los derechos agrarios heredados para que pasen al siguiente en el orden de preferencia.',
        keywords: ["repudio derechos","renuncia herencia ejidal","sucesión agraria"],
    },
    {
        id: 'agrario-enajenacion-parcela-v1',
        slug: 'cesion-derechos-agrarios-enajenacion',
        title: 'Contrato de Enajenación de Derechos Parcelarios',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/cesion-derechos-agrarios-enajenacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 80 Ley Agraria"],
        description: 'Contrato de compraventa (cesión onerosa) de derechos parcelarios entre ejidatarios o avecindados.',
        keywords: ["compraventa parcela","enajenación derechos parcelarios","ejido venta"],
    },
    {
        id: 'agrario-contestacion-demanda-v1',
        slug: 'contestacion-demanda-agraria',
        title: 'Contestación de Demanda Agraria',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/contestacion-demanda-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 178 Ley Agraria"],
        description: 'Escrito del demandado para contestar prestaciones, oponer excepciones y defensas en juicio agrario.',
        keywords: ["contestación agraria","juicio agrario","excepciones","TUA"],
    },
    {
        id: 'agrario-pruebas-v1',
        slug: 'ofrecimiento-pruebas-agrario',
        title: 'Ofrecimiento de Pruebas en Juicio Agrario',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/ofrecimiento-pruebas-agrario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 186-188 Ley Agraria"],
        description: 'Ofrecimiento de periciales topográficas, documentales e inspecciones para el desahogo judicial.',
        keywords: ["pruebas agrarias","pericial topográfica","TUA","documentales RAN"],
    },
    {
        id: 'agrario-recurso-revision-v1',
        slug: 'recurso-revision-tribunal-superior-agrario',
        title: 'Recurso de Revisión Agraria (TSA)',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/recurso-revision-tribunal-superior-agrario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 198, 199 Ley Agraria"],
        description: 'Recurso contra sentencias de los TUA que resuelvan restitución de tierras de núcleos de población.',
        keywords: ["revisión agraria","TSA","recurso impugnación agraria"],
    },
    {
        id: 'agrario-solicitud-ran-v1',
        slug: 'solicitud-certificado-parcelario-ran',
        title: 'Solicitud de Expedición de Certificado Parcelario',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/solicitud-certificado-parcelario-ran.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 16, 56 Ley Agraria"],
        description: 'Solicitud directa al Registro Agrario Nacional (RAN) para emitir el certificado parcelario o de uso común.',
        keywords: ["RAN","certificado parcelario","título de propiedad ejidal","trámite agrario"],
    },
    {
        id: 'agrario-dominio-pleno-v1',
        slug: 'solicitud-cambio-destino-tierras-dominio-pleno',
        title: 'Solicitud de Dominio Pleno (Cambio de Destino)',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/solicitud-cambio-destino-tierras-dominio-pleno.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 81, 82 Ley Agraria"],
        description: 'Solicitud formal para convocar a asamblea y desincorporar parcelas ejidales a dominio pleno (propiedad privada).',
        keywords: ["dominio pleno","privatizar ejido","tierras ejidales","propiedad privada"],
    },
    {
        id: 'agrario-alegatos-v1',
        slug: 'escrito-alegatos-juicio-agrario',
        title: 'Escrito de Alegatos en Juicio Agrario',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/escrito-alegatos-juicio-agrario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 189 Ley Agraria"],
        description: 'Presentación de conclusiones y argumentación final probatoria en el Tribunal Unitario Agrario.',
        keywords: ["alegatos TUA","conclusiones agrarias","juicio agrario"],
    },
    {
        id: 'agrario-reconocimiento-derechos-v1',
        slug: 'demanda-reconocimiento-derechos-agrarios',
        title: 'Demanda de Reconocimiento de Derechos Agrarios',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/demanda-reconocimiento-derechos-agrarios.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 12-16 Ley Agraria"],
        description: 'Juicio para obligar a la asamblea o comisariado a reconocer calidad de ejidatario o avecindado.',
        keywords: ["reconocimiento","avecindado","ejidatario judicial","derechos agrarios"],
    },
    {
        id: 'agrario-arrendamiento-medieria-v1',
        slug: 'contrato-arrendamiento-parcela-medieria',
        title: 'Contrato de Mediería o Aparcería (Arrendamiento Parcelario)',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/contrato-arrendamiento-parcela-medieria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 45, 79 Ley Agraria"],
        description: 'Contrato tradicional agrario para que un tercero trabaje la tierra a cambio de una participación de cosecha o renta.',
        keywords: ["aparcería","mediería","rentería tierras","renta de parcela","contrato agrícola"],
    },
    {
        id: 'agrario-usufructo-parcela-v1',
        slug: 'contrato-usufructo-parcela-ejidal',
        title: 'Contrato de Usufructo de Parcela Ejidal',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/contrato-usufructo-parcela-ejidal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 79 Ley Agraria"],
        description: 'Contrato para ceder el usufructo (ganancias y uso) de una parcela por tiempo determinado constituyendo una garantía para el acreedor (usufructuario).',
        keywords: ["usufructo parcela","garantía de siembra","terrenos ejidales"],
    },
    {
        id: 'agrario-audiencia-procuraduria-v1',
        slug: 'solicitud-audiencia-procuraduria-agraria',
        title: 'Solicitud de Asesoría / Audiencia ante Procuraduría Agraria',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/solicitud-audiencia-procuraduria-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 134-136 Ley Agraria"],
        description: 'Petición a la Procuraduría Agraria para solicitar representación jurídica gratuita o asesoría.',
        keywords: ["procuraduría agraria","representación agraria gratuita","visitador agrario"],
    },
    {
        id: 'agrario-queja-comisariado-v1',
        slug: 'queja-contra-comisariado-ejidal',
        title: 'Escrito de Queja contra Comisariado Ejidal',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/queja-contra-comisariado-ejidal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 32, 33 Ley Agraria"],
        description: 'Documento firmado por el Consejo de Vigilancia o asambleístas para destituir o amonestar al comisariado por abusos.',
        keywords: ["queja comisariado ejidal","destitución comisariado","malos manejos","consejo vigilancia"],
    },
    {
        id: 'agrario-convocatoria-asamblea-v1',
        slug: 'convocatoria-asamblea-ejidal',
        title: 'Convocatoria a Asamblea General de Ejidatarios',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/convocatoria-asamblea-ejidal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 24, 25 Ley Agraria"],
        description: 'Pizarrón formal ejidal, modelo de citatorio con primera o segunda convocatoria y orden del día.',
        keywords: ["convocatoria asamblea","asamblea ejidatarios","orden del día ejido"],
    },
    {
        id: 'agrario-acta-conciliacion-v1',
        slug: 'acta-conciliacion-agraria',
        title: 'Acta de Conciliación Agraria',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/acta-conciliacion-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 185-186 Ley Agraria"],
        description: 'Convenio formal entre partes en conflicto agrario (linderos, deudas, usufructos) ante Procuraduría Agraria para ser elevada a cosa juzgada.',
        keywords: ["conciliación agraria","convenio ejidatarios","fin de conflicto agrario"],
    },
    {
        id: 'agrario-prescripcion-adquisitiva-v1',
        slug: 'demanda-prescripcion-adquisitiva-agraria',
        title: 'Demanda de Prescripción Adquisitiva Agraria',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/demanda-prescripcion-adquisitiva-agraria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 48 Ley Agraria"],
        description: 'Juicio para regularizar tierras que han sido poseídas en calidad de ejidatario de buena fe por 5 años o mala fe por 10 años.',
        keywords: ["prescripción agraria","regularizar parcela","prescripción adquisitiva","usucapión agraria"],
    },
    {
        id: 'agrario-constancia-vigencia-v1',
        slug: 'solicitud-constancia-vigencia-derechos-ran',
        title: 'Solicitud Constancia de Vigencia de Derechos (RAN)',
        specialty: 'agrario',
        tier: 'v1',
        file: 'v1/agrario/solicitud-constancia-vigencia-derechos-ran.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 152 Ley Agraria"],
        description: 'Solicitud simple pero obligatoria para juicios, donde se pide al RAN historial del campesino.',
        keywords: ["vigencia derechos","historial RAN","registro ejidatario"],
    },
];
