
export const templatesV1_notarial: Template[] = [
    {
        id: 'notarial-poder-general-v1',
        slug: 'poder-general-actos-de-dominio',
        title: 'Poder General para Actos de Dominio',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/poder-general-actos-de-dominio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2553-2578 CCDF","Ley del Notariado CDMX"],
        description: 'Poder notarial que autoriza al apoderado a realizar todo acto de disposicion sobre bienes del poderdante.',
        keywords: ["poder notarial dominio","escritura poder","representacion legal amplia"],
    },
    {
        id: 'notarial-poder-administracion-v1',
        slug: 'poder-para-actos-administracion',
        title: 'Poder para Actos de Administración',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/poder-para-actos-administracion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2554 CCDF"],
        description: 'Poder notarial para gestionar bienes y negocios del poderdante sin facultad de enajenar.',
        keywords: ["poder administracion","mandato notarial","representacion negocios"],
    },
    {
        id: 'notarial-poder-especial-v1',
        slug: 'poder-especial-acto-determinado',
        title: 'Poder Especial para Acto Determinado',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/poder-especial-acto-determinado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 2553 CCDF"],
        description: 'Poder notarial limitado a un acto concreto, como firmar un contrato, comparecer en juicio o vender un bien especifico.',
        keywords: ["poder especial notarial","mandato acto especifico","poder limitado firmar contrato"],
    },
    {
        id: 'notarial-testamento-publico-v1',
        slug: 'testamento-publico-abierto',
        title: 'Testamento Público Abierto',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/testamento-publico-abierto.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1500-1530 CCDF","Ley del Notariado CDMX"],
        description: 'Ultima voluntad del testador dictada ante Notario Publico para distribuir su patrimonio.',
        keywords: ["testamento notarial","ultima voluntad notario","herencia testamento abierto"],
    },
    {
        id: 'notarial-acta-asamblea-sa-v1',
        slug: 'acta-asamblea-ordinaria-sa',
        title: 'Acta de Asamblea General Ordinaria de SA',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-asamblea-ordinaria-sa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 178-202 LGSM","Art. 143 LGSM"],
        description: 'Acta notariada que formaliza los acuerdos de la Asamblea Anual de Accionistas de una Sociedad Anonima.',
        keywords: ["acta asamblea SA","accionistas reunion anual","protocolizar asamblea notario"],
    },
    {
        id: 'notarial-fe-publica-hechos-v1',
        slug: 'acta-notarial-fe-publica-hechos',
        title: 'Acta Notarial de Fe Pública de Hechos',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-notarial-fe-publica-hechos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Notariado CDMX Art. 102"],
        description: 'Documento notarial que da fe de hechos percibidos directamente por el Notario, con plena fuerza probatoria.',
        keywords: ["acta notarial hechos","fe publica notario","notario constata hecho"],
    },
    {
        id: 'notarial-revocacion-poder-v1',
        slug: 'instrumento-revocacion-poder-notarial',
        title: 'Instrumento de Revocación de Poder Notarial',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/instrumento-revocacion-poder-notarial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2595-2598 CCDF"],
        description: 'Escritura notarial mediante la cual el poderdante deja sin efectos el poder anteriormente otorgado.',
        keywords: ["revocar poder notarial","cancelar mandato","revocacion poder ante notario"],
    },
    {
        id: 'notarial-protocolizacion-acta-v1',
        slug: 'protocolizacion-acta-extranjera',
        title: 'Protocolización de Acta Extranjera',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/protocolizacion-acta-extranjera.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convenio de La Haya de 1961 (Apostille)","Ley del Notariado"],
        description: 'Tramite notarial para darle validez en Mexico a un acta o documento publico proveniente del extranjero.',
        keywords: ["protocolizacion acta extranjera","apostilla documento","validar documento extranjero Mexico"],
    },
    {
        id: 'notarial-constitucion-sa-v1',
        slug: 'escritura-constitucion-sociedad-anonima',
        title: 'Escritura de Constitución de Sociedad Anónima',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/escritura-constitucion-sociedad-anonima.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 87-131 LGSM"],
        description: 'Protocolizacion notarial del acto de constitucion de una Sociedad Anonima con sus estatutos sociales.',
        keywords: ["constituir SA notario","escritura empresa SA","estatutos sociales anonima"],
    },
    {
        id: 'notarial-apostilla-v1',
        slug: 'solicitud-apostille-documento',
        title: 'Solicitud de Apostille de Documento Público',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/solicitud-apostille-documento.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convenio de La Haya de 1961"],
        description: 'Tramite para obtener el apostille de un documento publico mexicano para que surta efectos en el extranjero.',
        keywords: ["apostille Mexico","legalizar documento extranjero","convenio haya 1961"],
    },
    {
        id: 'notarial-declaracion-bienes-v1',
        slug: 'declaracion-inventario-bienes-sucesion',
        title: 'Declaración de Inventario de Bienes (Sucesión)',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/declaracion-inventario-bienes-sucesion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1700-1750 CCDF"],
        description: 'Documento notarial que lista y avalua todos los bienes que integran el acervo hereditario en una sucesion.',
        keywords: ["inventario sucesion","bienes herencia","declaracion patrimonio fallecido"],
    },
    {
        id: 'notarial-renuncia-herencia-v1',
        slug: 'renuncia-herencia-sucesion',
        title: 'Renuncia a la Herencia',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/renuncia-herencia-sucesion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1653-1660 CCDF"],
        description: 'Acto juridico notarial mediante el cual el heredero declara formalmente no aceptar la herencia.',
        keywords: ["renunciar herencia","repudio herencia","no aceptar herencia notario"],
    },
    {
        id: 'notarial-constitucion-srl-v1',
        slug: 'escritura-constitucion-srl',
        title: 'Escritura de Constitución de Sociedad de Responsabilidad Limitada',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/escritura-constitucion-srl.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 58-86 LGSM"],
        description: 'Protocolizacion notarial del acto de constitucion de una SRL con partes sociales y estatutos.',
        keywords: ["constituir SRL","escritura SRL notario","sociedad limitada estatutos"],
    },
    {
        id: 'notarial-acta-cierre-empresa-v1',
        slug: 'acta-notarial-disolucion-liquidacion',
        title: 'Acta Notarial de Disolución y Liquidación de Empresa',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-notarial-disolucion-liquidacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 229-249 LGSM"],
        description: 'Escritura notarial que formaliza la disolucion y liquidacion total de la sociedad.',
        keywords: ["disolucion empresa acta","liquidacion SA notario","cierre empresa escritura"],
    },
    {
        id: 'notarial-acta-nacimiento-copia-v1',
        slug: 'solicitud-copia-certificada-acta',
        title: 'Solicitud de Copia Certificada de Acta del Registro Civil',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/solicitud-copia-certificada-acta.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Registro Civil"],
        description: 'Tramite para obtener copia certificada de actas del Registro Civil (nacimiento, matrimonio, defuncion).',
        keywords: ["copia certificada acta nacimiento","registro civil copia","acta defuncion matrimonio"],
    },
    {
        id: 'notarial-instruccion-banco-v1',
        slug: 'carta-instruccion-banco-fideicomiso',
        title: 'Carta de Instrucción a Institución Fiduciaria',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/carta-instruccion-banco-fideicomiso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 381-407 LGTOC"],
        description: 'Instrucciones formales al Banco que actua como fiduciario para ejecutar actos especificos del fideicomiso.',
        keywords: ["instruccion fideicomiso banco","fiduciaria instruccion","ejecutar fideicomiso banco"],
    },
    {
        id: 'notarial-reconocimiento-firma-v1',
        slug: 'acta-reconocimiento-firma-impresiones',
        title: 'Acta de Reconocimiento de Firma',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-reconocimiento-firma-impresiones.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Notariado CDMX Art. 104"],
        description: 'Acto notarial en el que una persona reconoce ante el Notario la autenticidad de su firma en un documento.',
        keywords: ["reconocimiento firma notario","autenticar firma","fe de firma notarial"],
    },
    {
        id: 'notarial-acta-notificacion-v1',
        slug: 'acta-notificacion-notarial',
        title: 'Acta de Notificación Notarial',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-notificacion-notarial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Notariado CDMX Art. 102"],
        description: 'El Notario da fe de haber notificado personalmente a una persona un acto o requerimiento juridico.',
        keywords: ["notificacion notarial","notario da fe aviso","acta requerimiento notarial"],
    },
    {
        id: 'notarial-acta-embargo-v1',
        slug: 'acta-notarial-embargo-bienes',
        title: 'Acta Notarial de Aseguramiento de Bienes',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/acta-notarial-embargo-bienes.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1392 Codigo de Comercio","Ley del Notariado"],
        description: 'El Notario constata y da fe sobre el estado y existencia de bienes en el momento del embargo precautorio.',
        keywords: ["acta embargo notario","fe publica embargo bienes","notario aseguramiento"],
    },
    {
        id: 'notarial-certificacion-documentos-v1',
        slug: 'certificacion-copias-documentos',
        title: 'Certificación de Copias de Documentos',
        specialty: 'notarial',
        tier: 'v1',
        file: 'v1/notarial/certificacion-copias-documentos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Notariado CDMX Art. 99"],
        description: 'El Notario certifica que las copias presentadas son fiel reproduccion del documento original.',
        keywords: ["certificacion copias notario","fotocopia certificada","notario autenticar copia"],
    },
];
