
export const templatesV1_ambiental: Template[] = [
    {
        id: 'ambiental-denuncia-popular-v1',
        slug: 'denuncia-popular-profepa',
        title: 'Denuncia Popular Ambiental (PROFEPA)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/denuncia-popular-profepa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 189-204 LGEEPA"],
        description: 'Denuncia pública por hechos, actos u omisiones que producen desequilibrio ecológico o daños al ambiente.',
        keywords: ["denuncia popular","profepa","daño ambiental","LGEEPA"],
    },
    {
        id: 'ambiental-contestacion-profepa-v1',
        slug: 'contestacion-inspeccion-ambiental-profepa',
        title: 'Contestación a Visita de Inspección (PROFEPA)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/contestacion-inspeccion-ambiental-profepa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 167-169 LGEEPA"],
        description: 'Defensa administrativa inicial para desvirtuar las actas de inspección ambiental levantadas por la Profepa.',
        keywords: ["inspección profepa","contestación ambiental","acta visita ecológica"],
    },
    {
        id: 'ambiental-recurso-revision-semarnat-v1',
        slug: 'recurso-revision-semarnat',
        title: 'Recurso de Revisión Administrativa (SEMARNAT)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/recurso-revision-semarnat.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 176 LGEEPA","LFPA"],
        description: 'Recurso legal para impugnar resoluciones definitivas de la Semarnat que niegan permisos o imponen restricciones.',
        keywords: ["recurso semarnat","revisión ambiental","impugnación semarnat"],
    },
    {
        id: 'ambiental-solicitud-mia-v1',
        slug: 'solicitud-evaluacion-impacto-ambiental-mia',
        title: 'Solicitud de Evaluación de Impacto Ambiental (MIA)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/solicitud-evaluacion-impacto-ambiental-mia.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 28-30 LGEEPA"],
        description: 'Oficio de presentación de la Manifestación de Impacto Ambiental ante la DGEIRA para obras nuevas.',
        keywords: ["MIA semarnat","impacto ambiental","autorización ecológica","obra nueva ambiental"],
    },
    {
        id: 'ambiental-amparo-indirecto-v1',
        slug: 'amparo-indirecto-ambiental',
        title: 'Demanda de Amparo en Materia Ambiental (Interés Legítimo)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/amparo-indirecto-ambiental.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 4 Constitucional","Acuerdo de Escazú","Ley de Amparo"],
        description: 'Demanda de amparo indirecto promovida por ciudadanos bajo interés legítimo contra daños ecológicos.',
        keywords: ["amparo ambiental","interés legítimo ecología","derecho humano ambiente","acuerdo de escazú"],
    },
    {
        id: 'ambiental-alegatos-inspeccion-v1',
        slug: 'alegatos-procedimiento-inspeccion-ambiental',
        title: 'Alegatos en Procedimiento de Inspección Ambiental',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/alegatos-procedimiento-inspeccion-ambiental.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["LGEEPA","Reglamento de Inspección Ambiental"],
        description: 'Fase final probatoria para argumentar validez técnica ante multas eminentes por Profepa o estatales.',
        keywords: ["alegatos profepa","cierre de instrucción ambiental","multa profepa"],
    },
    {
        id: 'ambiental-juicio-nulidad-multa-v1',
        slug: 'demanda-nulidad-multa-ambiental',
        title: 'Juicio de Nulidad contra Multa Ambiental',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/demanda-nulidad-multa-ambiental.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Procedimiento Contencioso Administrativo"],
        description: 'Demanda ante el TFJA (Sala Especializada en Materia Ambiental si aplica) para anular multas por LGEEPA.',
        keywords: ["multa profepa tfja","nulidad multa ambiental","sala ambiental tfja"],
    },
    {
        id: 'ambiental-concesion-agua-v1',
        slug: 'solicitud-concesion-aguas-nacionales',
        title: 'Solicitud de Concesión de Aguas Nacionales',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/solicitud-concesion-aguas-nacionales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Aguas Nacionales"],
        description: 'Formato para solicitar volúmenes de extracción ante la CONAGUA para pozos o tomas fluviables.',
        keywords: ["concesión conagua","permiso de pozo","aguas nacionales","extracción agua"],
    },
    {
        id: 'ambiental-revocacion-estatal-v1',
        slug: 'recurso-revocacion-ambiental-estatal',
        title: 'Recurso de Revocación Ambiental (Estatal)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/recurso-revocacion-ambiental-estatal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Leyes Ambientales Estatales","Ley de Procedimiento Administrativo Estatal"],
        description: 'Defensa contra secretarías de ecología estatales por cierres de tiraderos o negocios locales.',
        keywords: ["secretaría medio ambiente estatal","revocación clausura ecología","multa ambiental municipio"],
    },
    {
        id: 'ambiental-denuncia-penal-v1',
        slug: 'denuncia-penal-delitos-ambientales',
        title: 'Denuncia Penal por Delitos Ambientales',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/denuncia-penal-delitos-ambientales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 414-423 Código Penal Federal"],
        description: 'Denuncia ante FGR por derrames químicos, deforestación, flora protegida, o contaminación penal.',
        keywords: ["delitos ambientales mp","fgr ecología","querella ecocidio","tala ilegal"],
    },
    {
        id: 'ambiental-medidas-urgentes-v1',
        slug: 'solicitud-medidas-urgentes-ambientales',
        title: 'Solicitud Medidas de Urgente Aplicación',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/solicitud-medidas-urgentes-ambientales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 170 LGEEPA"],
        description: 'Petición a Semarnat/Profepa para clausurar inmediatamente una industria por riesgo ecológico inminente.',
        keywords: ["medidas de seguridad profepa","clausura temporal","riesgo catastrófico","fuga de tóxicos"],
    },
    {
        id: 'ambiental-contestacion-conagua-v1',
        slug: 'contestacion-requerimiento-conagua',
        title: 'Contestación de Requerimiento (CONAGUA)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/contestacion-requerimiento-conagua.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Aguas Nacionales"],
        description: 'Desahogo a oficios por falta de pago de derechos de extracción de agua o inspecciones tarifarias.',
        keywords: ["requerimiento conagua","adeudo agua nacional","inspección conagua"],
    },
    {
        id: 'ambiental-permiso-forestal-v1',
        slug: 'solicitud-aprovechamiento-forestal',
        title: 'Solicitud de Permiso Aprovechamiento Forestal',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/solicitud-aprovechamiento-forestal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General de Desarrollo Forestal Sustentable"],
        description: 'Petición a SEMARNAT para aprovechamiento maderable legal o desmonte justificado.',
        keywords: ["permiso maderable","desmonte","semarnat tala"],
    },
    {
        id: 'ambiental-maltrato-animal-v1',
        slug: 'denuncia-maltrato-trafico-animal',
        title: 'Escrito de Denuncia por Maltrato Animal / Especies',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/denuncia-maltrato-trafico-animal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 420 CPF","Ley de Protección a los Animales"],
        description: 'Denuncia ciudadana especializada orientada a fauna protegida NOM-059-SEMARNAT o crueldad severa.',
        keywords: ["tráfico especies","maltrato animal","NOM-059","ecología animal"],
    },
    {
        id: 'ambiental-ruidos-v1',
        slug: 'queja-contaminacion-auditiva-ruidos',
        title: 'Queja por Contaminación Auditiva (Ruidos)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/queja-contaminacion-auditiva-ruidos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["NOM-081-ECOL-1994","Bando Policía y Buen Gobierno"],
        description: 'Escrito a ayuntamiento y ecología local clausurar fábricas o negocios ruidosos sobrepasando decibeles NOM.',
        keywords: ["ruido bar","contaminación auditiva","municipio ecología","NOM-081"],
    },
    {
        id: 'ambiental-responsabilidad-ley-v1',
        slug: 'demanda-responsabilidad-ambiental-civil',
        title: 'Demanda de Responsabilidad Ambiental',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/demanda-responsabilidad-ambiental-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Responsabilidad Ambiental (LFRA)"],
        description: 'Reclamo para obligar al pago de la reparación del ecosistema dañado, por vía judicial (Civil o Distrito).',
        keywords: ["LFRA","responsabilidad civil por daño ecológico","indemnización medio ambiente"],
    },
    {
        id: 'ambiental-residuos-peligrosos-v1',
        slug: 'contestacion-inspeccion-residuos-peligrosos',
        title: 'Contestación Visita (Residuos Peligrosos)',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/contestacion-inspeccion-residuos-peligrosos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley General para la Prevención y Gestión Integral de los Residuos (LGPGIR)"],
        description: 'Contestación para maquiladoras u hospitales acusados de mal manejo de RPBI o materiales tóxicos.',
        keywords: ["RPBI","residuos peligrosos","LGPGIR","clínica médica","maquiladora"],
    },
    {
        id: 'ambiental-exencion-mia-v1',
        slug: 'solicitud-exencion-mia-impacto-ambiental',
        title: 'Solicitud de Exención de MIA',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/solicitud-exencion-mia-impacto-ambiental.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Reglamento de Impacto Ambiental"],
        description: 'Oficio donde se argumenta y prueba que una pequeña obra industrial o rural NO requiere autorización de Impacto Ambiental.',
        keywords: ["exención MIA","oficio no aplicabilidad","semarnat permiso eximido"],
    },
    {
        id: 'ambiental-convenio-restauracion-v1',
        slug: 'convenio-restauracion-ambiental',
        title: 'Convenio de Restauración Ambiental',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/convenio-restauracion-ambiental.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["LGEEPA","Mecanismos Alternativos en Juicios Administrativos"],
        description: 'Contrato formal propuesto por la parte infractora a la Profepa proponiendo trabajo forestal o resarcimiento para condonar multas.',
        keywords: ["convenio profepa","conmutar multa ecológica","restauración ambiental compensación"],
    },
    {
        id: 'ambiental-reclamacion-denuncia-v1',
        slug: 'recurso-reclamacion-desechamiento-denuncia-popular',
        title: 'Recurso Reclamación Desechamiento Denuncia Popular',
        specialty: 'ambiental',
        tier: 'v1',
        file: 'v1/ambiental/recurso-reclamacion-desechamiento-denuncia-popular.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 199, 203 LGEEPA"],
        description: 'Recurso ante autoridad jerárquica porque la Profepa ignoró la queja ciudadana (denuncia popular) argumentando que no hay impacto.',
        keywords: ["desechamiento denuncia","profepa ignoró queja","reclamación ecología"],
    },
];
