
export const templatesV1_constitucional: Template[] = [
    {
        id: 'const-amparo-derechos-fundamentales-v1',
        slug: 'demanda-amparo-derechos-fundamentales',
        title: 'Demanda de Amparo por Violación de Derechos Fundamentales',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/demanda-amparo-derechos-fundamentales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1, 103, 107 CPEUM","Ley de Amparo"],
        description: 'Amparo indirecto para proteger derechos humanos fundamentales violados por autoridad.',
        keywords: ["amparo derechos fundamentales","amparo articulo 1","derechos humanos amparo"],
    },
    {
        id: 'const-accion-inconstitucionalidad-v1',
        slug: 'accion-inconstitucionalidad-ley',
        title: 'Acción de Inconstitucionalidad',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/accion-inconstitucionalidad-ley.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 105 Fr. II CPEUM","Ley Reglamentaria Art. 105"],
        description: 'Medio de control abstracto ante la SCJN para invalidar una ley por contravenir la Constitución.',
        keywords: ["accion inconstitucionalidad SCJN","invalidar ley inconstitucional","control concentrado"],
    },
    {
        id: 'const-controversia-constitucional-v1',
        slug: 'controversia-constitucional-federalismo',
        title: 'Controversia Constitucional',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/controversia-constitucional-federalismo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 105 Fr. I CPEUM"],
        description: 'Conflicto entre poderes o entre la Federación y estados resuelto por la SCJN.',
        keywords: ["controversia constitucional","conflicto poderes SCJN","federalismo controversia"],
    },
    {
        id: 'const-amparo-libertad-expresion-v1',
        slug: 'amparo-libertad-expresion-prensa',
        title: 'Amparo por Libertad de Expresión y Prensa',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-libertad-expresion-prensa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 6, 7 CPEUM","CADH Art. 13"],
        description: 'Acción de amparo para proteger la libre expresion de ideas y la libertad de prensa frente a censura.',
        keywords: ["amparo libertad expresion","censura prensa","periodista amparo"],
    },
    {
        id: 'const-amparo-ley-tributaria-v1',
        slug: 'amparo-contra-ley-fiscal-inconstitucional',
        title: 'Amparo contra Ley Tributaria Inconstitucional',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-contra-ley-fiscal-inconstitucional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 31 Fr. IV CPEUM","Ley de Amparo"],
        description: 'Amparo para impugnar una norma fiscal que viola los principios de proporcionalidad, equidad o legalidad tributaria.',
        keywords: ["amparo contra ley fiscal","inconstitucionalidad impuesto","proporcionalidad tributaria amparo"],
    },
    {
        id: 'const-amparo-audiencia-previa-v1',
        slug: 'amparo-garantia-audiencia-previa',
        title: 'Amparo por Violación a Garantía de Audiencia Previa',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-garantia-audiencia-previa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 14 CPEUM"],
        description: 'Amparo cuando la autoridad priva de derechos sin haber seguido un procedimiento previo con oportunidad de defensa.',
        keywords: ["garantia audiencia previa","articulo 14 amparo","privacion derechos sin audiencia"],
    },
    {
        id: 'const-queja-cndh-v1',
        slug: 'queja-ante-cndh',
        title: 'Queja ante la CNDH por Violación de Derechos Humanos',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/queja-ante-cndh.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 102 Apt. B CPEUM","Ley de la CNDH"],
        description: 'Queja formal ante la Comisión Nacional de Derechos Humanos por actos u omisiones de autoridades federales.',
        keywords: ["queja CNDH","derechos humanos queja federal","recomendacion CNDH"],
    },
    {
        id: 'const-amparo-seguridad-juridica-v1',
        slug: 'amparo-seguridad-juridica-exacta-aplicacion',
        title: 'Amparo por Seguridad Jurídica y Exacta Aplicación',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-seguridad-juridica-exacta-aplicacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 14, 16 CPEUM"],
        description: 'Amparo por actos de autoridad sin fundar ni motivar, o por aplicacion exacta de la ley penal por analogia.',
        keywords: ["exacta aplicacion ley penal","amparo articulo 16","fundamentacion motivacion"],
    },
    {
        id: 'const-amparo-discriminacion-v1',
        slug: 'amparo-discriminacion-igualdad',
        title: 'Amparo por Discriminación e Igualdad',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-discriminacion-igualdad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1, 4 CPEUM","Ley Federal para Prevenir la Discriminacion"],
        description: 'Amparo contra actos de autoridad que discriminan por raza, genero, religion, discapacidad u otra categoria sospechosa.',
        keywords: ["amparo discriminacion","igualdad ante la ley","categoria sospechosa amparo"],
    },
    {
        id: 'const-amparo-electoral-v1',
        slug: 'amparo-materia-electoral-excepcion',
        title: 'Amparo en Materia Electoral (Excepción)',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-materia-electoral-excepcion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 99 CPEUM","Ley de Amparo Art. 61 Fr. VII"],
        description: 'Amparo procedente en materia electoral solo para proteccion de derechos politico-electorales a titulo individual.',
        keywords: ["amparo electoral","derechos politicos articulo 99","voto amparo"],
    },
    {
        id: 'const-recurso-revision-amparo-v1',
        slug: 'recurso-revision-amparo-indirecto',
        title: 'Recurso de Revisión en Amparo',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/recurso-revision-amparo-indirecto.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 80-96 Ley de Amparo"],
        description: 'Recurso contra sentencias de Juez de Distrito en amparo indirecto, ante el TCC o la SCJN.',
        keywords: ["revision amparo","recurso juicio amparo","TCC revision amparo"],
    },
    {
        id: 'const-cumplimiento-sentencia-amparo-v1',
        slug: 'promocion-cumplimiento-sentencia-amparo',
        title: 'Promoción de Cumplimiento de Sentencia de Amparo',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/promocion-cumplimiento-sentencia-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 192-200 Ley de Amparo"],
        description: 'Instancia cuando la autoridad responsable se niega o demora el cumplimiento de la senten de amparo.',
        keywords: ["cumplimiento sentencia amparo","inejecucion amparo","repeticion acto reclamado"],
    },
    {
        id: 'const-amparo-penal-directo-v1',
        slug: 'demanda-amparo-directo-penal',
        title: 'Demanda de Amparo Directo Penal',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/demanda-amparo-directo-penal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 158-191 Ley de Amparo"],
        description: 'Amparo directo ante el TCC contra sentencia definitiva de juicio penal oral que causa agravio al condenado.',
        keywords: ["amparo directo penal","amparo sentencia penal","impugnar condena penal"],
    },
    {
        id: 'const-suspension-definitiva-v1',
        slug: 'solicitud-suspension-definitiva-amparo',
        title: 'Solicitud de Suspensión Definitiva del Acto Reclamado',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/solicitud-suspension-definitiva-amparo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 125-138 Ley de Amparo"],
        description: 'Medida cautelar para que el acto de autoridad no se ejecute mientras se resuelve el amparo.',
        keywords: ["suspension definitiva amparo","medida cautelar amparo","paralizar acto autoridad"],
    },
    {
        id: 'const-demanda-amparo-laboral-v1',
        slug: 'demanda-amparo-directo-laboral',
        title: 'Demanda de Amparo Directo Laboral',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/demanda-amparo-directo-laboral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 158-191 Ley de Amparo","Art. 123 CPEUM"],
        description: 'Amparo directo ante el TCC contra laudo o sentencia definitiva del Tribunal Laboral.',
        keywords: ["amparo directo laboral","impugnar laudo","sentencia laboral amparo"],
    },
    {
        id: 'const-queja-estado-v1',
        slug: 'queja-cedh-comision-estatal',
        title: 'Queja ante Comisión Estatal de Derechos Humanos',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/queja-cedh-comision-estatal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 102 Apt. B CPEUM","Ley Estatal de Derechos Humanos"],
        description: 'Queja por actos de autoridades estatales o municipales que violen derechos humanos.',
        keywords: ["queja CEDH estatal","derechos humanos estado","comision estatal ombudsman"],
    },
    {
        id: 'const-amparo-civil-directo-v1',
        slug: 'demanda-amparo-directo-civil',
        title: 'Demanda de Amparo Directo Civil',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/demanda-amparo-directo-civil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 158-191 Ley de Amparo"],
        description: 'Amparo directo ante el TCC contra sentencia definitiva de juicio civil que causa agravio al perdidoso.',
        keywords: ["amparo directo civil","impugnar sentencia civil","TCC amparo civil"],
    },
    {
        id: 'const-amparo-propiedad-v1',
        slug: 'amparo-contra-expropiacion',
        title: 'Amparo contra Expropiación',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-contra-expropiacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 14, 27 CPEUM","Ley de Expropiacion"],
        description: 'Amparo para impugnar decreto expropiatorio de inmueble por falta de causa de utilidad publica o indemnizacion justa.',
        keywords: ["amparo expropiacion","impugnar decreto expropiatorio","indemnizacion expropiacion"],
    },
    {
        id: 'const-amparo-interlocutorio-v1',
        slug: 'amparo-contra-auto-interlocutorio',
        title: 'Amparo contra Auto Interlocutorio',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/amparo-contra-auto-interlocutorio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 107 Fr. II CPEUM","Art. 170 Ley de Amparo"],
        description: 'Amparo directo excepcionalmente procedente contra autos que tengan efectos de imposible reparacion.',
        keywords: ["amparo auto interlocutorio","imposible reparacion amparo","acto dentro del juicio"],
    },
    {
        id: 'const-impugnacion-reforma-constitucional-v1',
        slug: 'mecanismo-control-reforma-constitucional',
        title: 'Escrito sobre Mecanismo de Control de Reforma Constitucional',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/mecanismo-control-reforma-constitucional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 135, 105 CPEUM"],
        description: 'Analisis juridico del mecanismo de control de las reformas constitucionales y su procedibilidad ante la SCJN.',
        keywords: ["reforma constitucional control","SCJN impugnar reforma","poder constituyente permanente"],
    },
    {
        id: 'const-habeas-data-v1',
        slug: 'accion-habeas-data-proteccion-datos',
        title: 'Acción de Habeas Data',
        specialty: 'constitucional',
        tier: 'v1',
        file: 'v1/constitucional/accion-habeas-data-proteccion-datos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 6 CPEUM","Ley Federal de Proteccion de Datos Personales"],
        description: 'Accion para exigir acceso, rectificacion, cancelacion u oposicion al tratamiento de datos personales en poder de autoridades.',
        keywords: ["habeas data","acceso datos personales ARCO","derechos ARCO autoridad"],
    },
];
