
export const templatesV1_inmobiliario: Template[] = [
    {
        id: 'inmob-contrato-compraventa-v1',
        slug: 'contrato-compraventa-inmueble',
        title: 'Contrato de Compraventa de Inmueble',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-compraventa-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2248-2322 CCDF"],
        description: 'Contrato formalizado ante Notario por el que se transmite la propiedad de un bien inmueble.',
        keywords: ["compraventa casa","contrato inmueble","escritura compraventa"],
    },
    {
        id: 'inmob-arrendamiento-comercial-v1',
        slug: 'contrato-arrendamiento-local-comercial',
        title: 'Contrato de Arrendamiento de Local Comercial',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-arrendamiento-local-comercial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2398-2496 CCDF"],
        description: 'Contrato de alquiler de local comercial con cláusulas de renta, depósito, vigencia y usos permitidos.',
        keywords: ["arrendamiento local","renta negocio","contrato comercial arrendatario"],
    },
    {
        id: 'inmob-contrato-arrendamiento-habitacional-v1',
        slug: 'contrato-arrendamiento-casa-habitacion',
        title: 'Contrato de Arrendamiento de Casa Habitación',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-arrendamiento-casa-habitacion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2398-2496 CCDF"],
        description: 'Contrato de renta de inmueble para habitación con depósito, garantía y plazo mínimo de un año.',
        keywords: ["renta casa habitacion","contrato arrendamiento vivienda","inquilino propietario"],
    },
    {
        id: 'inmob-demanda-desocupacion-v1',
        slug: 'demanda-desocupacion-arrendatario',
        title: 'Demanda de Desocupación por Falta de Pago',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/demanda-desocupacion-arrendatario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2478, 2489 CCDF"],
        description: 'Acción del propietario para recuperar su inmueble por falta de pago de renta o vencimiento del contrato.',
        keywords: ["desocupacion falta de pago","rescision arrendamiento","inquilino moroso"],
    },
    {
        id: 'inmob-contrato-obra-v1',
        slug: 'contrato-obra-a-precio-alzado',
        title: 'Contrato de Obra a Precio Alzado',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-obra-a-precio-alzado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2616-2641 CCDF"],
        description: 'Contrato donde el constructor se compromete a terminar la obra por un precio fijo independientemente del costo final.',
        keywords: ["contrato obra precio alzado","constructor precio fijo","obra privada contrato"],
    },
    {
        id: 'inmob-hipoteca-v1',
        slug: 'contrato-hipoteca-inmobiliaria',
        title: 'Contrato de Hipoteca Inmobiliaria',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-hipoteca-inmobiliaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2893-2943 CCDF"],
        description: 'Constitución de garantía hipotecaria sobre inmueble en respaldo de un crédito o préstamo.',
        keywords: ["hipoteca casa","garantia inmobiliaria","credito hipotecario contrato"],
    },
    {
        id: 'inmob-servidumbre-v1',
        slug: 'contrato-servidumbre-paso',
        title: 'Contrato de Servidumbre de Paso',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-servidumbre-paso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1057-1106 CCDF"],
        description: 'Acuerdo que concede a una propiedad vecina el derecho de paso por el inmueble sirviente.',
        keywords: ["servidumbre de paso","derecho acceso vecino","predio sirviente dominante"],
    },
    {
        id: 'inmob-donacion-inmueble-v1',
        slug: 'contrato-donacion-inmueble',
        title: 'Contrato de Donación de Inmueble',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-donacion-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2332-2399 CCDF"],
        description: 'Transmision gratuita e irrevocable de la propiedad de un inmueble de donante a donatario.',
        keywords: ["donacion inmueble","regalo propiedad","escritura donacion"],
    },
    {
        id: 'inmob-subdivision-v1',
        slug: 'solicitud-autorizacion-subdivision-inmueble',
        title: 'Solicitud de Autorización de Subdivisión',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/solicitud-autorizacion-subdivision-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Desarrollo Urbano CDMX","Arts. 100-120 RCDF"],
        description: 'Trámite ante la autoridad urbanística para dividir un predio en dos o más lotes independientes.',
        keywords: ["subdivision predio","autorización SEDUVI","lotes independientes"],
    },
    {
        id: 'inmob-permuta-v1',
        slug: 'contrato-permuta-inmuebles',
        title: 'Contrato de Permuta de Inmuebles',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-permuta-inmuebles.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2327-2331 CCDF"],
        description: 'Intercambio de dos inmuebles entre dos propietarios, con o sin compensación económica.',
        keywords: ["permuta inmueble","intercambio propiedades","swap inmobiliario"],
    },
    {
        id: 'inmob-fideicomiso-garantia-v1',
        slug: 'contrato-fideicomiso-garantia-inmobiliaria',
        title: 'Contrato de Fideicomiso en Garantía',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-fideicomiso-garantia-inmobiliaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 381-407 LGTOC"],
        description: 'Fideicomiso donde el inmueble queda en fideicomiso como garantía de un crédito, sin pasar al acreedor.',
        keywords: ["fideicomiso garantia","credito inmobiliario fideicomiso","garantia fiduciaria"],
    },
    {
        id: 'inmob-aviso-privacidad-v1',
        slug: 'aviso-privacidad-inmobiliaria',
        title: 'Aviso de Privacidad para Inmobiliaria',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/aviso-privacidad-inmobiliaria.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley Federal de Proteccion de Datos Personales"],
        description: 'Aviso legal que la inmobiliaria proporciona al cliente explicando el tratamiento de sus datos personales.',
        keywords: ["aviso privacidad inmobiliaria","datos personales clientes","LFPDPPP inmobiliaria"],
    },
    {
        id: 'inmob-contrato-desarrollo-v1',
        slug: 'contrato-desarrollo-inmobiliario',
        title: 'Contrato de Desarrollo Inmobiliario (Joint Venture)',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-desarrollo-inmobiliario.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2688-2735 CCDF","Ley General de Bienes Nacionales"],
        description: 'Acuerdo de asociacion para el desarrollo conjunto de un proyecto inmobiliario con division de utilidades.',
        keywords: ["joint venture inmobiliario","desarrollo conjunto inmueble","proyecto inmobiliario asociacion"],
    },
    {
        id: 'inmob-uso-suelo-v1',
        slug: 'solicitud-cambio-uso-suelo',
        title: 'Solicitud de Cambio de Uso de Suelo',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/solicitud-cambio-uso-suelo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Desarrollo Urbano CDMX","PGDU 2020"],
        description: 'Peticion formal ante la autoridad municipal o delegacional para modificar el uso permitido de un predio.',
        keywords: ["cambio uso suelo","SEDUVI uso habitacional","autorizacion uso comercial"],
    },
    {
        id: 'inmob-condominio-reglamento-v1',
        slug: 'reglamento-condominio',
        title: 'Reglamento Interno de Condominio',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/reglamento-condominio.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Propiedad en Condominio CDMX"],
        description: 'Reglamento que regula la convivencia y uso de areas comunes en un desarrollo en condominio.',
        keywords: ["reglamento condominio","asambleas condominos","administrador condominio"],
    },
    {
        id: 'inmob-carta-instruccion-v1',
        slug: 'carta-instruccion-notario-compraventa',
        title: 'Carta de Instrucción al Notario',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/carta-instruccion-notario-compraventa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Notariado CDMX"],
        description: 'Instrucciones específicas del cliente al Notario para protocolizar la compraventa inmobiliaria.',
        keywords: ["instruccion notario","protocolo compraventa","escrituracion inmueble"],
    },
    {
        id: 'inmob-licencia-construccion-v1',
        slug: 'solicitud-licencia-construccion',
        title: 'Solicitud de Licencia de Construcción',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/solicitud-licencia-construccion.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Reglamento de Construcciones CDMX","NOM-001-SEDE-2012"],
        description: 'Trámite formal ante la autoridad local para obtener el permiso de edificación de una obra nueva.',
        keywords: ["licencia construccion","permiso obra","CDMX licencia edificar"],
    },
    {
        id: 'inmob-rescision-promesa-v1',
        slug: 'demanda-rescision-promesa-compraventa',
        title: 'Demanda de Rescisión de Promesa de Compraventa',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/demanda-rescision-promesa-compraventa.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2243-2247 CCDF"],
        description: 'Acción para dejar sin efectos la promesa de compraventa cuando la contraparte incumple formalizarla.',
        keywords: ["rescision promesa compraventa","devolucion enganche","incumplimiento contrato previo"],
    },
    {
        id: 'inmob-dacion-pago-v1',
        slug: 'contrato-dacion-en-pago-inmueble',
        title: 'Contrato de Dación en Pago de Inmueble',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-dacion-en-pago-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2095-2097 CCDF"],
        description: 'Acuerdo donde el deudor entrega un inmueble a su acreedor en substitución del pago de la deuda.',
        keywords: ["dacion en pago","pago con inmueble","cancelar deuda con propiedad"],
    },
    {
        id: 'inmobiliario-contrato-promesa-v1',
        slug: 'contrato-promesa-compraventa-inmueble',
        title: 'Contrato de Promesa de Compraventa de Inmueble',
        specialty: 'inmobiliario',
        tier: 'v1',
        file: 'v1/inmobiliario/contrato-promesa-compraventa-inmueble.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2243-2247 CCDF"],
        description: 'Contrato previo a la escrituración que obliga a ambas partes a formalizar la compraventa.',
        keywords: ["promesa compraventa","pre-contrato inmueble","enganche inmueble"],
    },
];
