
export const templatesV1_concursal: Template[] = [
    {
        id: 'concursal-solicitud-concurso-mercantil-v1',
        slug: 'solicitud-declaracion-concurso-mercantil',
        title: 'Solicitud de Declaracion de Concurso Mercantil',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-declaracion-concurso-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 9-20 Ley de Concursos Mercantiles"],
        description: 'Solicitud voluntaria del comerciante ante el juez para ser declarado en concurso mercantil por estado general de incumplimiento.',
        keywords: ["concurso mercantil voluntario","quiebra empresa Mexico","insolvencia declaracion"],
    },
    {
        id: 'concursal-demanda-acreedor-v1',
        slug: 'demanda-concurso-mercantil-por-acreedor',
        title: 'Demanda de Concurso Mercantil por Acreedor',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/demanda-concurso-mercantil-por-acreedor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 21-30 LCM"],
        description: 'Demanda interpuesta por un acreedor para que el juez declare en concurso mercantil al deudor insolvente.',
        keywords: ["concurso mercantil acreedor","quiebra demanda creditor","insolvencia deudor comerciante"],
    },
    {
        id: 'concursal-reconocimiento-credito-v1',
        slug: 'solicitud-reconocimiento-credito-concurso',
        title: 'Solicitud de Reconocimiento de Credito en Concurso',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-reconocimiento-credito-concurso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 121-150 LCM"],
        description: 'Solicitud del acreedor ante el conciliador para que su credito sea incluido en la lista definitiva del concurso.',
        keywords: ["reconocimiento credito concurso","lista definitiva acreedores","conciliador concursal"],
    },
    {
        id: 'concursal-impugnacion-lista-v1',
        slug: 'impugnacion-lista-definitiva-creditos',
        title: 'Impugnacion de la Lista Definitiva de Creditos',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/impugnacion-lista-definitiva-creditos.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 151-170 LCM"],
        description: 'Recurso contra la lista definitiva de creditos reconocidos en el concurso por error u omision.',
        keywords: ["impugnar lista creditos concurso","objetar credito reconocido","prelacion acreedores impugnacion"],
    },
    {
        id: 'concursal-convenio-concursal-v1',
        slug: 'propuesta-convenio-concursal-deudor',
        title: 'Propuesta de Convenio Concursal por el Deudor',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/propuesta-convenio-concursal-deudor.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 157-187 LCM"],
        description: 'Propuesta formal del deudor concursado a sus acreedores para reestructurar sus obligaciones y evitar la quiebra.',
        keywords: ["convenio concursal propuesta","quita acreedores concurso","reestructura deuda evitar quiebra"],
    },
    {
        id: 'concursal-quiebra-solicitud-v1',
        slug: 'solicitud-declaracion-quiebra',
        title: 'Solicitud de Declaracion en Quiebra',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-declaracion-quiebra.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 188-210 LCM"],
        description: 'Solicitud para que el juez declare la quiebra tras el fracaso de la etapa de conciliacion en el concurso mercantil.',
        keywords: ["declaracion quiebra empresa","fase quiebra concurso Mexico","sindico quiebra LCM"],
    },
    {
        id: 'concursal-accion-retroaccion-v1',
        slug: 'accion-retroaccion-quiebra',
        title: 'Accion de Retroaccion de Actos en el Periodo Sospechoso',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/accion-retroaccion-quiebra.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 112-120 LCM"],
        description: 'Demanda para que el sindico rescinda actos del deudor realizados en el periodo sospechoso previo al concurso.',
        keywords: ["retroaccion quiebra","periodo sospechoso concurso","rescindir actos fraudulentos insolvencia"],
    },
    {
        id: 'concursal-incidente-separacion-bienes-v1',
        slug: 'incidente-separacion-bienes-tercero',
        title: 'Incidente de Separacion de Bienes de Tercero en Concurso',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/incidente-separacion-bienes-tercero.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 71-80 LCM"],
        description: 'Solicitud de un tercero para que se separen bienes propios que se encuentran en posesion del deudor concursado.',
        keywords: ["separacion bienes tercero concurso","reivindicacion quiebra","bienes propios masa concursal"],
    },
    {
        id: 'concursal-objecion-credito-privilegiado-v1',
        slug: 'objecion-credito-privilegiado',
        title: 'Objecion de Credito con Preferencia Privilegiada',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/objecion-credito-privilegiado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 217-230 LCM"],
        description: 'Escrito de un acreedor objetando la prelacion privilegiada otorgada a otro credito en el concurso.',
        keywords: ["objetar credito privilegiado","prelacion acreedores concurso","credito subordinado impugnar"],
    },
    {
        id: 'concursal-demanda-responsabilidad-administradores-v1',
        slug: 'demanda-responsabilidad-administradores-quiebra',
        title: 'Demanda de Responsabilidad contra Administradores en Quiebra',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/demanda-responsabilidad-administradores-quiebra.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 271-285 LCM"],
        description: 'Accion del sindico para demandar a administradores cuya conducta agrave o cause la insolvencia del comerciante.',
        keywords: ["responsabilidad administradores quiebra","sindico demanda directores","culpa gerencial insolvencia"],
    },
    {
        id: 'concursal-cesion-credito-concurso-v1',
        slug: 'cesion-credito-concurso-mercantil',
        title: 'Convenio de Cesion de Credito en Concurso Mercantil',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/cesion-credito-concurso-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 2029-2042 CCDF","LCM"],
        description: 'Acuerdo por el que un acreedor cede su credito reconocido en el concurso a un tercero adquirente.',
        keywords: ["cesion credito concurso","compra cartera concursal","adquirir credito quiebra"],
    },
    {
        id: 'concursal-suspension-pagos-v1',
        slug: 'solicitud-suspension-pagos-visitador',
        title: 'Solicitud de Suspension de Pagos ante Visitador',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-suspension-pagos-visitador.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 41-70 LCM"],
        description: 'Solicitud del deudor para que el visitador recomiende la suspension de obligaciones de pago mientras dura la visita.',
        keywords: ["suspension pagos concurso","visitador concursal LCM","moratoria obligaciones deudor"],
    },
    {
        id: 'concursal-enajenacion-activos-v1',
        slug: 'solicitud-enajenacion-activos-concurso',
        title: 'Solicitud de Enajenacion de Activos del Concursado',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-enajenacion-activos-concurso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 211-240 LCM"],
        description: 'Solicitud del sindico para autorizar la venta de activos de la masa concursal y distribuir el producto entre acreedores.',
        keywords: ["venta activos quiebra","enajenacion masa concursal","sindico venta bienes empresa"],
    },
    {
        id: 'concursal-pago-preferente-laboral-v1',
        slug: 'solicitud-pago-creditos-laborales-preferentes',
        title: 'Solicitud de Pago Preferente de Creditos Laborales',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-pago-creditos-laborales-preferentes.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 224 LCM","Art. 113 LFT"],
        description: 'Peticion de los trabajadores para que sus creditos laborales se paguen con prioridad absoluta en el concurso.',
        keywords: ["credito laboral preferente quiebra","trabajadores concurso mercantil","salarios quiebra empresa"],
    },
    {
        id: 'concursal-oposicion-concurso-v1',
        slug: 'oposicion-declaracion-concurso-mercantil',
        title: 'Oposicion a la Declaracion de Concurso Mercantil',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/oposicion-declaracion-concurso-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 31-40 LCM"],
        description: 'Escrito del deudor oponiendo pruebas contra la solicitud de concurso presentada por un acreedor.',
        keywords: ["oposicion concurso mercantil","contestar demanda quiebra","refutar insolvencia empresa"],
    },
    {
        id: 'concursal-acuerdo-preconcursal-v1',
        slug: 'acuerdo-extrajudicial-preconcursal',
        title: 'Acuerdo Extrajudicial Preconcursal con Acreedores',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/acuerdo-extrajudicial-preconcursal.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 338-346 LCM"],
        description: 'Convenio privado deudor-acreedores para reestructurar la deuda sin acudir al proceso concursal judicial.',
        keywords: ["acuerdo preconcursal extrajudicial","reestructura privada deuda","evitar quiebra convenio acreedores"],
    },
    {
        id: 'concursal-acumulacion-juicios-v1',
        slug: 'solicitud-acumulacion-juicios-concurso',
        title: 'Solicitud de Acumulacion de Juicios al Concurso Mercantil',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/solicitud-acumulacion-juicios-concurso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 65-70 LCM"],
        description: 'Solicitud para que todos los juicios individuales contra el concursado se concentren en el expediente concursal.',
        keywords: ["acumulacion juicios concurso","fuero de atraccion quiebra","concentrar demandas concursal"],
    },
    {
        id: 'concursal-plan-prepack-v1',
        slug: 'plan-reestructura-prepack-concurso',
        title: 'Plan de Reestructura Pre-Pactado (Prepack) en Concurso',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/plan-reestructura-prepack-concurso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 338-370 LCM"],
        description: 'Plan de reestructura negociado antes del concurso y presentado para aprobacion rapida en el proceso.',
        keywords: ["prepack concurso Mexico","reestructura rapida empresa","convenio previo acreedores concurso"],
    },
    {
        id: 'concursal-clausura-expediente-v1',
        slug: 'clausura-expediente-concurso-mercantil',
        title: 'Solicitud de Clausura del Expediente Concursal',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/clausura-expediente-concurso-mercantil.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 286-300 LCM"],
        description: 'Peticion del sindico al juez para declarar concluido el concurso mercantil tras liquidar el pasivo.',
        keywords: ["clausura concurso mercantil","fin quiebra extincion","cierre expediente concursal sindico"],
    },
    {
        id: 'concursal-reporte-sindico-v1',
        slug: 'informe-trimestral-sindico-concurso',
        title: 'Informe Trimestral del Sindico en Concurso Mercantil',
        specialty: 'concursal',
        tier: 'v1',
        file: 'v1/concursal/informe-trimestral-sindico-concurso.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 252-270 LCM"],
        description: 'Reporte periodico del sindico al juez sobre el estado de la masa concursal y las gestiones realizadas.',
        keywords: ["informe sindico concurso","reporte masa concursal","administracion quiebra sindico"],
    },
];
