
export const templatesV1_arbitraje: Template[] = [
    {
        id: 'arbitraje-convenio-arbitral-v1',
        slug: 'convenio-arbitral-clausula-comercial',
        title: 'Convenio Arbitral / Clausula de Arbitraje Comercial',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/convenio-arbitral-clausula-comercial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1416 Codigo de Comercio","LMACI"],
        description: 'Clausula o convenio independiente por el que las partes someten futuras o presentes controversias a arbitraje.',
        keywords: ["clausula arbitraje contrato","convenio arbitral comercial","arbitraje pacto partes comercio"],
    },
    {
        id: 'arbitraje-demanda-arbitral-v1',
        slug: 'demanda-arbitral-ante-centro-arbitraje',
        title: 'Demanda Arbitral ante Centro de Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/demanda-arbitral-ante-centro-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1424-1435 Codigo de Comercio"],
        description: 'Escrito inicial de la parte actora sometiendo la controversia al tribunal arbitral designado.',
        keywords: ["demanda arbitral camaras","inicio arbitraje comercial","escrito inicial arbitraje"],
    },
    {
        id: 'arbitraje-contestacion-demanda-v1',
        slug: 'contestacion-demanda-arbitral',
        title: 'Contestacion de Demanda Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/contestacion-demanda-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1435-1437 Codigo de Comercio"],
        description: 'Respuesta formal de la parte demandada a la demanda arbitral, con sus excepciones y defensas.',
        keywords: ["contestar demanda arbitral","respuesta arbitraje comercial","excepciones demanda arbitral"],
    },
    {
        id: 'arbitraje-reconvencion-v1',
        slug: 'reconvencion-en-procedimiento-arbitral',
        title: 'Reconvencion en Procedimiento Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/reconvencion-en-procedimiento-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1437 Bis Codigo de Comercio"],
        description: 'Contrademanda interpuesta por la parte demandada contra el demandante en el mismo procedimiento arbitral.',
        keywords: ["reconvencion arbitraje","contrademanda arbitral","demandada reconviene arbitraje"],
    },
    {
        id: 'arbitraje-medida-cautelar-v1',
        slug: 'solicitud-medida-cautelar-arbitraje',
        title: 'Solicitud de Medida Cautelar en Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/solicitud-medida-cautelar-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1425 Codigo de Comercio","Art. 17 Reglamento CAM"],
        description: 'Solicitud ante el tribunal arbitral para ordenar medidas provisionales que protejan los derechos de la parte durante el arbitraje.',
        keywords: ["medida cautelar arbitraje","suspension provisional arbitral","orden cautelar tribunal arbitral"],
    },
    {
        id: 'arbitraje-recusacion-arbitro-v1',
        slug: 'recusacion-arbitro-parcialidad',
        title: 'Recusacion de Arbitro por Falta de Imparcialidad',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/recusacion-arbitro-parcialidad.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1428-1430 Codigo de Comercio"],
        description: 'Procedimiento para apartar a un arbitro del tribunal cuando existan razones fundadas de parcialidad o falta de independencia.',
        keywords: ["recusacion arbitro","imparcialidad arbitraje","apartar arbitro procedimiento"],
    },
    {
        id: 'arbitraje-laudo-parcial-v1',
        slug: 'solicitud-laudo-parcial-arbitraje',
        title: 'Solicitud de Laudo Parcial en Arbitraje Comercial',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/solicitud-laudo-parcial-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1438-1445 Codigo de Comercio"],
        description: 'Peticion para que el tribunal arbitral emita un laudo parcial sobre cuestiones de competencia o responsabilidad.',
        keywords: ["laudo parcial arbitraje","resolucion parcial tribunal arbitral","bifurcacion proceso arbitral"],
    },
    {
        id: 'arbitraje-ejecucion-laudo-v1',
        slug: 'solicitud-ejecucion-laudo-arbitral',
        title: 'Solicitud de Reconocimiento y Ejecucion de Laudo Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/solicitud-ejecucion-laudo-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1461 Codigo de Comercio","Convencion de Nueva York 1958"],
        description: 'Solicitud ante el juez de distrito para que reconozca y ejecute coactivamente el laudo arbitral firme.',
        keywords: ["ejecutar laudo arbitral mexico","reconocimiento laudo arbitral","homologacion laudo arbitraje"],
    },
    {
        id: 'arbitraje-nulidad-laudo-v1',
        slug: 'accion-nulidad-laudo-arbitral',
        title: 'Accion de Nulidad de Laudo Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/accion-nulidad-laudo-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1457 Codigo de Comercio"],
        description: 'Demanda ante el juez de distrito para anular un laudo arbitral por violacion al debido proceso o por causas legales.',
        keywords: ["nulidad laudo arbitral mexico","impugnar laudo arbitraje","anular laudo arbitral codigo comercio"],
    },
    {
        id: 'arbitraje-acuerdo-terminos-referencia-v1',
        slug: 'acta-mision-terminos-referencia-arbitraje',
        title: 'Acta de Mision (Terminos de Referencia del Arbitraje)',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/acta-mision-terminos-referencia-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 23 Reglamento de Arbitraje CCI","Arts. 1435 Codigo Comercio"],
        description: 'Documento que delimita el objeto del arbitraje, las pretensiones de las partes y el programa del procedimiento.',
        keywords: ["acta mision arbitraje","terminos referencia arbitral","scope arbitraje comercial"],
    },
    {
        id: 'arbitraje-audiencia-pruebas-v1',
        slug: 'escrito-ofrecimiento-pruebas-arbitraje',
        title: 'Escrito de Ofrecimiento de Pruebas en Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/escrito-ofrecimiento-pruebas-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1438-1442 Codigo de Comercio","Reglas IBA de Prueba"],
        description: 'Escrito de una parte ofreciendo y relacionando sus medios de prueba al tribunal arbitral.',
        keywords: ["pruebas arbitraje comercial","ofrecimiento prueba arbitral","exhibir documentos arbitraje"],
    },
    {
        id: 'arbitraje-alegatos-arbitral-v1',
        slug: 'alegatos-post-audiencia-arbitraje',
        title: 'Alegatos Post-Audiencia en Procedimiento Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/alegatos-post-audiencia-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1442-1444 Codigo de Comercio"],
        description: 'Escrito de alegatos finales que una parte presenta al tribunal arbitral tras el desahogo de pruebas.',
        keywords: ["alegatos arbitraje","conclusiones arbitral","escrito final arbitraje comercial"],
    },
    {
        id: 'arbitraje-conciliacion-previa-v1',
        slug: 'conciliacion-previa-arbitraje-comercial',
        title: 'Acuerdo de Conciliacion Previa al Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/conciliacion-previa-arbitraje-comercial.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1416 Codigo de Comercio"],
        description: 'Convenio por el que las partes intentan una conciliacion amigable antes de iniciar el procedimiento arbitral.',
        keywords: ["conciliacion arbitraje comercial","mediacion previa arbitraje","arreglo amigable antes arbitraje"],
    },
    {
        id: 'arbitraje-excepcion-incompetencia-v1',
        slug: 'excepcion-jurisdiccion-incompetencia-arbitral',
        title: 'Excepcion de Incompetencia del Tribunal Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/excepcion-jurisdiccion-incompetencia-arbitral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1432 Codigo de Comercio — Kompetenz-Kompetenz"],
        description: 'Excepcion que opone una parte cuestionando la competencia del tribunal arbitral para conocer la controversia.',
        keywords: ["excepcion incompetencia arbitral","jurisdiccion tribunal arbitral","kompetenz kompetenz mexico"],
    },
    {
        id: 'arbitraje-prueba-pericial-v1',
        slug: 'solicitud-perito-tercero-neutral-arbitraje',
        title: 'Solicitud de Perito Tercero Neutral en Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/solicitud-perito-tercero-neutral-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 1440-1441 Codigo de Comercio","Reglas IBA"],
        description: 'Peticion al tribunal arbitral para designar un perito neutral que emita dictamen sobre cuestiones tecnicas.',
        keywords: ["perito arbitraje neutral","experto tecnico arbitral","dictamen pericial arbitraje comercial"],
    },
    {
        id: 'arbitraje-convenio-transaccional-v1',
        slug: 'convenio-transaccional-fin-arbitraje',
        title: 'Convenio Transaccional con Solicitud de Consentir Laudo',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/convenio-transaccional-fin-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1446 Codigo de Comercio"],
        description: 'Acuerdo de las partes para terminar el arbitraje mediante transaccion, solicitando al tribunal un laudo por consentimiento.',
        keywords: ["transaccion fin arbitraje","laudo por consentimiento","arreglo amigable arbitraje resolucion"],
    },
    {
        id: 'arbitraje-internacional-v1',
        slug: 'solicitud-arbitraje-internacional-ciac',
        title: 'Solicitud de Arbitraje Internacional ante el CIAC',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/solicitud-arbitraje-internacional-ciac.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Convencion de Nueva York 1958","LMACI Mexico"],
        description: 'Solicitud de inicio de arbitraje internacional conforme a las reglas del Centro Internacional de Arbitraje Comercial.',
        keywords: ["arbitraje internacional mexico","CIAC arbitraje","arbitraje comercio internacional"],
    },
    {
        id: 'arbitraje-amparo-laudo-v1',
        slug: 'amparo-indirecto-contra-auto-judicial-arbitraje',
        title: 'Amparo contra Resolucion Judicial en Materia Arbitral',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/amparo-indirecto-contra-auto-judicial-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 107 CPEUM","Art. 1457 Codigo de Comercio"],
        description: 'Juicio de amparo indirecto contra la resolucion del juez de distrito que reconoce o niega ejecutar un laudo arbitral.',
        keywords: ["amparo laudo arbitral","impugnar decision judicial arbitraje","amparo arbitraje comercio"],
    },
    {
        id: 'arbitraje-clausula-escalonada-v1',
        slug: 'clausula-resolucion-escalonada-negociacion-mediacion-arbitraje',
        title: 'Clausula de Resolucion Escalonada: Negociacion-Mediacion-Arbitraje',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/clausula-resolucion-escalonada-negociacion-mediacion-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 1416 Codigo de Comercio","LMACI"],
        description: 'Clausula multi-nivel que obliga a las partes a agotar negociacion y mediacion antes de acudir al arbitraje.',
        keywords: ["clausula escalonada contrato","mediacion antes arbitraje","resolucion disputas multi-nivel"],
    },
    {
        id: 'arbitraje-mediacion-cam-v1',
        slug: 'mediacion-cam-previa-arbitraje',
        title: 'Solicitud de Mediacion ante el CAM (Previa al Arbitraje)',
        specialty: 'arbitraje',
        tier: 'v1',
        file: 'v1/arbitraje/mediacion-cam-previa-arbitraje.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley de Mediacion CDMX","Reglamento de Mediacion CAM"],
        description: 'Solicitud formal para iniciar un proceso de mediacion ante el Centro de Arbitraje de Mexico como paso previo al arbitraje.',
        keywords: ["mediacion cam mexico","mediacion comercial previa arbitraje","conciliacion cam empresa"],
    },
];
