
export const templatesV1_laboral: Template[] = [
    {
        id: 'laboral-demanda-despido-v1',
        slug: 'demanda-despido-injustificado',
        title: 'Demanda por Despido Injustificado',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-despido-injustificado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 48, 49, 50 LFT"],
        description: 'Demanda ante Tribunal Laboral exigiendo reinstalación o indemnización constitucional.',
        keywords: ["despido injustificado","reinstalación laboral","indemnización 90 días"],
    },
    {
        id: 'laboral-rescision-trabajador-v1',
        slug: 'demanda-rescision-contrato-laboral-trabajador',
        title: 'Demanda de Rescisión Imputable al Patrón',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-rescision-contrato-laboral-trabajador.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 51 LFT"],
        description: 'El trabajador rescinde por causa grave del patrón (humillaciones, falta de pago) y cobra indemnización.',
        keywords: ["rescisión imputable patrón","acoso laboral","falta de pago salario"],
    },
    {
        id: 'laboral-horas-extras-v1',
        slug: 'demanda-horas-extras-no-pagadas',
        title: 'Demanda de Horas Extras No Pagadas',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-horas-extras-no-pagadas.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 66-68 LFT"],
        description: 'Reclamación de tiempo extraordinario trabajado y no remunerado al doble o triple.',
        keywords: ["horas extras laboral","tiempo extra doble","remuneración jornada"],
    },
    {
        id: 'laboral-vacaciones-v1',
        slug: 'demanda-vacaciones-prima-vacacional',
        title: 'Demanda de Vacaciones y Prima Vacacional',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-vacaciones-prima-vacacional.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 76-80 LFT"],
        description: 'Reclamación de días de vacaciones no disfrutados o prima vacacional no pagada al 25%.',
        keywords: ["vacaciones laborales","prima vacacional 25%","días de descanso"],
    },
    {
        id: 'laboral-aguinaldo-v1',
        slug: 'demanda-aguinaldo-no-pagado',
        title: 'Demanda de Aguinaldo',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-aguinaldo-no-pagado.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 87 LFT"],
        description: 'Reclamación de 15 días de salario mínimo o proporcional de aguinaldo no pagado.',
        keywords: ["aguinaldo ley federal trabajo","gratificación anual","15 días pago"],
    },
    {
        id: 'laboral-seguridad-imss-v1',
        slug: 'demanda-inscripcion-imss',
        title: 'Demanda de Inscripción al IMSS',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-inscripcion-imss.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 12, 15 Ley del Seguro Social"],
        description: 'Obliga al patrón a dar de alta al trabajador ante el IMSS con el salario correcto.',
        keywords: ["alta IMSS","seguro social trabajador","inscripción patrón"],
    },
    {
        id: 'laboral-acoso-sexual-v1',
        slug: 'demanda-acoso-sexual-laboral',
        title: 'Demanda por Acoso Sexual Laboral',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-acoso-sexual-laboral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 47 Fr. IX LFT","NOM-035-STPS"],
        description: 'Acción legal del trabajador victim de acoso u hostigamiento sexual por parte del empleador o compañeros.',
        keywords: ["hostigamiento sexual laboral","acoso trabajo","NOM-035","ambiente hostil"],
    },
    {
        id: 'laboral-riesgo-trabajo-v1',
        slug: 'demanda-riesgo-trabajo-accidente',
        title: 'Demanda por Riesgo de Trabajo',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-riesgo-trabajo-accidente.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 473-502 LFT"],
        description: 'Indemnización al trabajador por accidente o enfermedad de trabajo ocurrida en el centro de trabajo.',
        keywords: ["riesgo trabajo","accidente laboral","enfermedad profesional","incapacidad permanente"],
    },
    {
        id: 'laboral-partes-proporcionales-v1',
        slug: 'demanda-partes-proporcionales-prestaciones',
        title: 'Demanda de Partes Proporcionales de Prestaciones',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-partes-proporcionales-prestaciones.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 76, 80, 87 LFT"],
        description: 'Reclamación de partes proporcionales de aguinaldo, vacaciones y prima cuando la relación duró menos de un año.',
        keywords: ["partes proporcionales","prestaciones prorrateadas","liquidación proporcional"],
    },
    {
        id: 'laboral-trabajo-excepcion-v1',
        slug: 'contestacion-demanda-laboral-patron',
        title: 'Contestación de Demanda Laboral (Patrón)',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/contestacion-demanda-laboral-patron.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 878-879 LFT"],
        description: 'Escrito de defensa del patrón oponiendo justificación del despido o negando la relación laboral.',
        keywords: ["contestación despido","defensa patrón laboral","negativa relación laboral"],
    },
    {
        id: 'laboral-pruebas-v1',
        slug: 'ofrecimiento-pruebas-laboral',
        title: 'Ofrecimiento de Pruebas en Juicio Laboral',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/ofrecimiento-pruebas-laboral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 783-803 LFT"],
        description: 'Presentación de documentales, testimoniales, confesionales e inspecciones en la audiencia de juicio.',
        keywords: ["pruebas laborales","confesional juicio laboral","documental patrón"],
    },
    {
        id: 'laboral-emplazamiento-huelga-v1',
        slug: 'emplazamiento-huelga',
        title: 'Pliego Petitorio y Emplazamiento a Huelga',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/emplazamiento-huelga.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 450-469 LFT"],
        description: 'Documento sindical formal exigiendo mejoras de contrato y emplazando a huelga en caso de rechazo.',
        keywords: ["emplazamiento huelga","pliego petitorio","sindicato patrón"],
    },
    {
        id: 'laboral-reglamento-interior-v1',
        slug: 'impugnacion-reglamento-interior-trabajo',
        title: 'Queja contra Reglamento Interior de Trabajo',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/impugnacion-reglamento-interior-trabajo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 422-425 LFT"],
        description: 'Impugnación ante la Secretaría del Trabajo de una clausula del reglamento que viola derechos laborales.',
        keywords: ["reglamento interior trabajo","impugnar claúsula patronal","derechos laborales reglamento"],
    },
    {
        id: 'laboral-convenio-liquidacion-v1',
        slug: 'convenio-liquidacion-laboral',
        title: 'Convenio de Liquidación Laboral',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/convenio-liquidacion-laboral.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 33, 987 LFT"],
        description: 'Acuerdo ratificado ante el Tribunal para dar finiquito total a la relación laboral.',
        keywords: ["convenio liquidación laboral","finiquito ratificado tribunal","liquidación total"],
    },
    {
        id: 'laboral-demanda-seguro-desempleo-v1',
        slug: 'solicitud-seguro-desempleo',
        title: 'Solicitud de Seguro de Desempleo',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/solicitud-seguro-desempleo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Ley del Seguro de Desempleo CDMX","Art. 123 CPEUM"],
        description: 'Trámite ante autoridades locales para acceder a la cobertura de desempleo involuntario.',
        keywords: ["seguro desempleo CDMX","apoyo desempleado","prestación desempleo"],
    },
    {
        id: 'laboral-modificacion-condiciones-v1',
        slug: 'demanda-modificacion-condiciones-trabajo',
        title: 'Demanda por Modificación Unilateral de Condiciones',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-modificacion-condiciones-trabajo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 51 Fr. V LFT"],
        description: 'Cuando el patrón cambia unilateralmente salario, horario, funciones o lugar de trabajo sin consentimiento.',
        keywords: ["modificación condiciones trabajo","cambio unilateral","rebaja salario"],
    },
    {
        id: 'laboral-infonavit-v1',
        slug: 'reclamacion-aportaciones-infonavit',
        title: 'Reclamación de Aportaciones INFONAVIT',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/reclamacion-aportaciones-infonavit.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 29 Ley del INFONAVIT"],
        description: 'Reclamación al patrón por omisión de entero de las aportaciones al fondo del trabajador.',
        keywords: ["INFONAVIT aportaciones","fondo vivienda patrón","omisión subcuenta INFONAVIT"],
    },
    {
        id: 'laboral-reinstalacion-v1',
        slug: 'demanda-reinstalacion-puesto',
        title: 'Demanda de Reinstalación en el Puesto',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-reinstalacion-puesto.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 48 LFT"],
        description: 'Acción específica cuando el trabajador elige reinstalación en vez de indemnización constitucional.',
        keywords: ["reinstalación laboral","volver al trabajo","negativa reinstalación"],
    },
    {
        id: 'laboral-contrato-colectivo-v1',
        slug: 'demanda-celebracion-contrato-colectivo',
        title: 'Demanda de Celebración de Contrato Colectivo',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-celebracion-contrato-colectivo.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Arts. 386-403 LFT"],
        description: 'Acción sindical para obligar al patrón a negociar y firmar un contrato colectivo de trabajo.',
        keywords: ["contrato colectivo trabajo","cct sindicato patrón","negociacion colectiva"],
    },
    {
        id: 'laboral-pago-diferencias-v1',
        slug: 'demanda-diferencias-salariales',
        title: 'Demanda de Pago de Diferencias Salariales',
        specialty: 'laboral',
        tier: 'v1',
        file: 'v1/laboral/demanda-diferencias-salariales.html',
        price: 0,
        priceLabel: 'Gratis',
        legalBasis: ["Art. 82-90 LFT"],
        description: 'Reclamación cuando el patrón paga menos del salario contractual o mínimo establecido.',
        keywords: ["diferencias salariales","salario bajo lo pactado","salario mínimo incumplido"],
    },
];
